/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.TaiKhoan.TaiKhoanDAO;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dat
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        getRootPane().setDefaultButton(btnLog); 
        // --- nền ảnh cho pWest ---
        pWest.removeAll();
        pWest.setLayout(new java.awt.BorderLayout());
        BackgroundPanel bgLeft = new BackgroundPanel("/icon/mainBackground.png"); // đổi đường dẫn ảnh nếu khác
        pWest.add(bgLeft, java.awt.BorderLayout.CENTER);
        pWest.revalidate();
        pWest.repaint();
        // -------------------------
        loginLayout();
        setLocationRelativeTo(null);
        setTitle("Phần mềm quản lý cửa hàng tiện lợi");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // Khuyến nghị: bật khử răng cưa font (không bắt buộc)
        System.setProperty("awt.useSystemAAFontSettings", "on");
        System.setProperty("swing.aatext", "true");

        // Tạo UI trên EDT
        javax.swing.SwingUtilities.invokeLater(() -> {
            try {
                initFlatlaf(); // FlatLaf + custom defaults (đã có sẵn trong lớp)
            } catch (Exception ex) {
                ex.printStackTrace(); // Nếu FlatLaf lỗi, vẫn mở UI với LAF mặc định
            }
            new Login().setVisible(true); // Mở form đăng nhập
        });
    }

    private static void initFlatlaf() {
        FlatLaf.registerCustomDefaultsSource("Style");
        FlatIntelliJLaf.setup();

    }

    private void loginLayout() {
        txtTK.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new FlatSVGIcon("./icon/username.svg"));
        txtMK.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new FlatSVGIcon("./icon/password.svg"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        pWest = new javax.swing.JPanel();
        anh = new javax.swing.JLabel();
        pCenter = new javax.swing.JPanel();
        pTitle = new javax.swing.JPanel();
        pTitleTop = new javax.swing.JPanel();
        pTitleDown = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pLogin = new javax.swing.JPanel();
        pTK = new javax.swing.JPanel();
        lblTK = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        cachDong1 = new javax.swing.JPanel();
        cachDong3 = new javax.swing.JPanel();
        pMK = new javax.swing.JPanel();
        lblMK = new javax.swing.JLabel();
        cachDong2 = new javax.swing.JPanel();
        cachDong4 = new javax.swing.JPanel();
        txtMK = new javax.swing.JPasswordField();
        pButton = new javax.swing.JPanel();
        pButtonTop = new javax.swing.JPanel();
        btnLog = new javax.swing.JButton();
        pButtonDown = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setResizable(false);

        Panel.setBackground(new java.awt.Color(0, 153, 102));
        Panel.setPreferredSize(new java.awt.Dimension(1200, 600));
        Panel.setLayout(new java.awt.BorderLayout());

        pWest.setBackground(new java.awt.Color(255, 255, 255));
        pWest.setAlignmentX(0.0F);
        pWest.setAlignmentY(0.0F);
        pWest.setMinimumSize(new java.awt.Dimension(800, 600));
        pWest.setPreferredSize(new java.awt.Dimension(800, 600));
        pWest.setLayout(new java.awt.BorderLayout());

        anh.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        anh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Icon/mainBackground.png"))); // NOI18N
        anh.setAlignmentY(0.0F);
        pWest.add(anh, java.awt.BorderLayout.CENTER);

        Panel.add(pWest, java.awt.BorderLayout.LINE_START);

        pCenter.setBackground(new java.awt.Color(255, 255, 255));
        pCenter.setPreferredSize(new java.awt.Dimension(400, 422));
        pCenter.setLayout(new java.awt.BorderLayout());

        pTitle.setBackground(new java.awt.Color(255, 255, 255));
        pTitle.setMinimumSize(new java.awt.Dimension(400, 220));
        pTitle.setPreferredSize(new java.awt.Dimension(400, 220));
        pTitle.setLayout(new java.awt.BorderLayout());

        pTitleTop.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pTitleTopLayout = new javax.swing.GroupLayout(pTitleTop);
        pTitleTop.setLayout(pTitleTopLayout);
        pTitleTopLayout.setHorizontalGroup(
            pTitleTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pTitleTopLayout.setVerticalGroup(
            pTitleTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        pTitle.add(pTitleTop, java.awt.BorderLayout.CENTER);

        pTitleDown.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ĐĂNG NHẬP");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pTitleDownLayout = new javax.swing.GroupLayout(pTitleDown);
        pTitleDown.setLayout(pTitleDownLayout);
        pTitleDownLayout.setHorizontalGroup(
            pTitleDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTitleDownLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pTitleDownLayout.setVerticalGroup(
            pTitleDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTitleDownLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pTitle.add(pTitleDown, java.awt.BorderLayout.SOUTH);

        pCenter.add(pTitle, java.awt.BorderLayout.NORTH);

        pLogin.setBackground(new java.awt.Color(255, 255, 255));
        pLogin.setMinimumSize(new java.awt.Dimension(400, 160));
        pLogin.setPreferredSize(new java.awt.Dimension(400, 200));
        pLogin.setLayout(new java.awt.BorderLayout(10, 10));

        pTK.setBackground(new java.awt.Color(255, 255, 255));
        pTK.setMinimumSize(new java.awt.Dimension(400, 100));
        pTK.setLayout(new java.awt.BorderLayout());

        lblTK.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTK.setText("Tên tài khoản:");
        lblTK.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblTK.setMaximumSize(new java.awt.Dimension(400, 50));
        lblTK.setMinimumSize(new java.awt.Dimension(400, 50));
        lblTK.setPreferredSize(new java.awt.Dimension(400, 50));
        pTK.add(lblTK, java.awt.BorderLayout.NORTH);

        txtTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTK.setMinimumSize(new java.awt.Dimension(380, 50));
        txtTK.setPreferredSize(new java.awt.Dimension(400, 50));
        txtTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTKActionPerformed(evt);
            }
        });
        pTK.add(txtTK, java.awt.BorderLayout.CENTER);

        cachDong1.setBackground(new java.awt.Color(255, 255, 255));
        cachDong1.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout cachDong1Layout = new javax.swing.GroupLayout(cachDong1);
        cachDong1.setLayout(cachDong1Layout);
        cachDong1Layout.setHorizontalGroup(
            cachDong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cachDong1Layout.setVerticalGroup(
            cachDong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pTK.add(cachDong1, java.awt.BorderLayout.LINE_END);

        cachDong3.setBackground(new java.awt.Color(255, 255, 255));
        cachDong3.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout cachDong3Layout = new javax.swing.GroupLayout(cachDong3);
        cachDong3.setLayout(cachDong3Layout);
        cachDong3Layout.setHorizontalGroup(
            cachDong3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cachDong3Layout.setVerticalGroup(
            cachDong3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pTK.add(cachDong3, java.awt.BorderLayout.LINE_START);

        pLogin.add(pTK, java.awt.BorderLayout.NORTH);

        pMK.setBackground(new java.awt.Color(255, 255, 255));
        pMK.setMinimumSize(new java.awt.Dimension(400, 100));
        pMK.setPreferredSize(new java.awt.Dimension(400, 100));
        pMK.setLayout(new java.awt.BorderLayout());

        lblMK.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMK.setText("Mật khẩu:");
        lblMK.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblMK.setMaximumSize(new java.awt.Dimension(400, 50));
        lblMK.setMinimumSize(new java.awt.Dimension(400, 50));
        lblMK.setPreferredSize(new java.awt.Dimension(400, 50));
        pMK.add(lblMK, java.awt.BorderLayout.PAGE_START);

        cachDong2.setBackground(new java.awt.Color(255, 255, 255));
        cachDong2.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout cachDong2Layout = new javax.swing.GroupLayout(cachDong2);
        cachDong2.setLayout(cachDong2Layout);
        cachDong2Layout.setHorizontalGroup(
            cachDong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        cachDong2Layout.setVerticalGroup(
            cachDong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pMK.add(cachDong2, java.awt.BorderLayout.LINE_END);

        cachDong4.setBackground(new java.awt.Color(255, 255, 255));
        cachDong4.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout cachDong4Layout = new javax.swing.GroupLayout(cachDong4);
        cachDong4.setLayout(cachDong4Layout);
        cachDong4Layout.setHorizontalGroup(
            cachDong4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        cachDong4Layout.setVerticalGroup(
            cachDong4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pMK.add(cachDong4, java.awt.BorderLayout.LINE_START);

        txtMK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMK.setMinimumSize(new java.awt.Dimension(400, 50));
        txtMK.setPreferredSize(new java.awt.Dimension(400, 50));
        pMK.add(txtMK, java.awt.BorderLayout.CENTER);

        pLogin.add(pMK, java.awt.BorderLayout.SOUTH);

        pCenter.add(pLogin, java.awt.BorderLayout.CENTER);

        pButton.setBackground(new java.awt.Color(255, 255, 255));
        pButton.setMinimumSize(new java.awt.Dimension(400, 200));
        pButton.setPreferredSize(new java.awt.Dimension(400, 200));
        pButton.setLayout(new java.awt.BorderLayout());

        pButtonTop.setBackground(new java.awt.Color(255, 255, 255));
        pButtonTop.setMinimumSize(new java.awt.Dimension(400, 60));
        pButtonTop.setPreferredSize(new java.awt.Dimension(400, 40));

        btnLog.setBackground(new java.awt.Color(15, 204, 102));
        btnLog.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLog.setForeground(new java.awt.Color(255, 255, 255));
        btnLog.setText("Đăng nhập");
        btnLog.setPreferredSize(new java.awt.Dimension(200, 40));
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });
        pButtonTop.add(btnLog);

        pButton.add(pButtonTop, java.awt.BorderLayout.CENTER);

        pButtonDown.setBackground(new java.awt.Color(255, 255, 255));
        pButtonDown.setMinimumSize(new java.awt.Dimension(400, 100));
        pButtonDown.setPreferredSize(new java.awt.Dimension(400, 100));

        javax.swing.GroupLayout pButtonDownLayout = new javax.swing.GroupLayout(pButtonDown);
        pButtonDown.setLayout(pButtonDownLayout);
        pButtonDownLayout.setHorizontalGroup(
            pButtonDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pButtonDownLayout.setVerticalGroup(
            pButtonDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pButton.add(pButtonDown, java.awt.BorderLayout.SOUTH);

        pCenter.add(pButton, java.awt.BorderLayout.SOUTH);

        Panel.add(pCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTKActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTKActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtTKActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:
        String user = txtTK.getText().trim();
        String pass = new String(txtMK.getPassword()).trim();

        // --- Kiểm tra hợp lệ ---
        if (user.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tài khoản để trống. Vui lòng nhập tên tài khoản!");
            txtTK.requestFocus();
            return;
        }

        if (pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mật khẩu để trống. Vui lòng nhập mật khẩu!");
            txtMK.requestFocus();
            return;
        }

        // Sửa điều kiện logic: phải là "< 8 || > 16"
        if (pass.length() < 8 || pass.length() > 16) {
            JOptionPane.showMessageDialog(this, "Mật khẩu phải từ 8-16 ký tự!");
            txtMK.requestFocus();
            return;
        }

        // Username chỉ chữ, số hoặc gạch dưới
        if (!user.matches("^[a-zA-Z0-9_]{3,}$")) {
            JOptionPane.showMessageDialog(this, "Tên tài khoản không hợp lệ. Chỉ chứa chữ, số, hoặc dấu gạch dưới!");
            txtTK.requestFocus();
            return;
        }

        // --- Đăng nhập ---
        TaiKhoanDAO dao = new TaiKhoanDAO();
        java.util.Optional<Entity.TaiKhoan.TaiKhoan> oTk = dao.checkDangNhap(user, pass);

        if (oTk.isPresent()) {
            Entity.TaiKhoan.TaiKhoan tk = oTk.get();

            // Truyền TaiKhoan vào Main (constructor Main(TaiKhoan))
            new Main(tk).setVisible(true);
            this.dispose(); // đóng form Login
        } else {
            JOptionPane.showMessageDialog(this, "Sai tài khoản hoặc mật khẩu!");
            txtMK.requestFocus();
            txtMK.selectAll();
        }
    }// GEN-LAST:event_btnLogActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel anh;
    private javax.swing.JButton btnLog;
    private javax.swing.JPanel cachDong1;
    private javax.swing.JPanel cachDong2;
    private javax.swing.JPanel cachDong3;
    private javax.swing.JPanel cachDong4;
    private javax.swing.JLabel lblMK;
    private javax.swing.JLabel lblTK;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pButton;
    private javax.swing.JPanel pButtonDown;
    private javax.swing.JPanel pButtonTop;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPanel pMK;
    private javax.swing.JPanel pTK;
    private javax.swing.JPanel pTitle;
    private javax.swing.JPanel pTitleDown;
    private javax.swing.JPanel pTitleTop;
    private javax.swing.JPanel pWest;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables


private static class BackgroundPanel extends javax.swing.JPanel {
    private java.awt.Image bg;

    public BackgroundPanel(String resourcePath) {
        setOpaque(true);
        setLayout(new java.awt.BorderLayout()); // có thể add child đè lên
        java.net.URL url = getClass().getResource(resourcePath);
        if (url == null)
            throw new IllegalArgumentException("Không tìm thấy ảnh: " + resourcePath);
        bg = new javax.swing.ImageIcon(url).getImage();
    }

    @Override
    protected void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g);
        if (bg == null)
            return;

        java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
        g2.setRenderingHint(java.awt.RenderingHints.KEY_INTERPOLATION,
                java.awt.RenderingHints.VALUE_INTERPOLATION_BILINEAR);

        int W = getWidth(), H = getHeight();
        int w = bg.getWidth(null), h = bg.getHeight(null);

        // COVER: phóng to để phủ kín, cắt phần thừa
        double s = Math.max((double) W / w, (double) H / h);
        int sw = (int) (w * s), sh = (int) (h * s);
        int x = (W - sw) / 2, y = (H - sh) / 2;

        g2.drawImage(bg, x, y, sw, sh, null);
        g2.dispose();
    }
}
}

