/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.TaiKhoan.TaiKhoanDAO;
import Entity.TaiKhoan.TaiKhoan;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Dat
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        loginLayout();
        setLocationRelativeTo(null);
        setTitle("Phần mềm quản lý cửa hàng tiện lợi");

    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            initFlatlaf();
//            new Login().setVisible(true);
//
////            new Main().setVisible(true);
//
//        });
//    }

    private static void initFlatlaf() {
        FlatLaf.registerCustomDefaultsSource("Style");
        FlatIntelliJLaf.setup();

    }

    private void loginLayout() {
        txtTK.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new FlatSVGIcon("./icon/username.svg"));
        txtMK.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new FlatSVGIcon("./icon/password.svg"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        pWest = new javax.swing.JPanel();
        anh = new javax.swing.JLabel();
        pCenter = new javax.swing.JPanel();
        tilte = new javax.swing.JLabel();
        lblTK = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        lblMK = new javax.swing.JLabel();
        txtMK = new javax.swing.JPasswordField();
        btnLog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        Panel.setBackground(new java.awt.Color(0, 153, 102));
        Panel.setLayout(new java.awt.BorderLayout());

        pWest.setBackground(new java.awt.Color(0, 204, 0));
        pWest.setAlignmentX(0.0F);
        pWest.setAlignmentY(0.0F);
        pWest.setPreferredSize(new java.awt.Dimension(600, 600));
        pWest.setLayout(new java.awt.BorderLayout());

        anh.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        anh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/AnhMain.jpg"))); // NOI18N
        anh.setAlignmentY(0.0F);
        pWest.add(anh, java.awt.BorderLayout.CENTER);

        Panel.add(pWest, java.awt.BorderLayout.LINE_START);

        pCenter.setBackground(new java.awt.Color(255, 255, 255));
        pCenter.setPreferredSize(new java.awt.Dimension(400, 422));

        tilte.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        tilte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tilte.setText("ĐĂNG NHẬP");
        tilte.setAlignmentY(0.0F);
        tilte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblTK.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTK.setText("Tài Khoản");

        txtTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTK.setForeground(new java.awt.Color(51, 51, 51));
        txtTK.setSelectionColor(new java.awt.Color(0, 153, 153));
        txtTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTKActionPerformed(evt);
            }
        });

        lblMK.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMK.setText("Mật Khẩu");

        txtMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMKActionPerformed(evt);
            }
        });

        btnLog.setBackground(new java.awt.Color(0, 102, 102));
        btnLog.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLog.setForeground(new java.awt.Color(255, 255, 255));
        btnLog.setText("ĐĂNG NHẬP");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCenterLayout = new javax.swing.GroupLayout(pCenter);
        pCenter.setLayout(pCenterLayout);
        pCenterLayout.setHorizontalGroup(
            pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCenterLayout.createSequentialGroup()
                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCenterLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTK)
                            .addComponent(txtTK)
                            .addComponent(lblMK)
                            .addComponent(txtMK)
                            .addComponent(btnLog, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)))
                    .addGroup(pCenterLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(tilte, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pCenterLayout.setVerticalGroup(
            pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCenterLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(tilte)
                .addGap(18, 18, 18)
                .addComponent(lblTK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        Panel.add(pCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        String user = txtTK.getText().trim();
        String pass = new String(txtMK.getPassword()).trim();

        TaiKhoanDAO dao = new TaiKhoanDAO();
//        TaiKhoan tk = dao.dangNhap(user, pass);

        // Kiểm tra để trống
        if (user.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tài khoản để trống. Vui lòng nhập tên tài khoản!");
            txtTK.requestFocus();
            return;
        }

        if (pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mật khẩu để trống. Vui lòng nhập mật khẩu!");
            txtMK.requestFocus();
            return;
        }

        // Kiểm tra mật khẩu ít nhất 8 ký tự
        if (pass.length() < 8 && pass.length() > 16) {
            JOptionPane.showMessageDialog(this, "Mật khẩu phải từ 8-16 ký tự!");
            txtMK.requestFocus();
            return;
        }

        // Nếu cần regex thêm như kiểm tra user chỉ có chữ cái/số:
        if (!user.matches("^[a-zA-Z0-9_]{3,}$")) {
            JOptionPane.showMessageDialog(this, "Tên tài khoản không hợp lệ. Chỉ chứa chữ, số, hoặc dấu gạch dưới và ít nhất 3 ký tự!");
            txtTK.requestFocus();
            return;
        }

//        if (tk != null) {
//            new Main(tk).setVisible(true);
//            this.dispose(); // Đóng form đăng nhập
//        } else {
//            JOptionPane.showMessageDialog(this, "Sai tài khoản hoặc mật khẩu!");
//        }
        
    }//GEN-LAST:event_btnLogActionPerformed

    private void txtMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMKActionPerformed

    private void txtTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel anh;
    private javax.swing.JButton btnLog;
    private javax.swing.JLabel lblMK;
    private javax.swing.JLabel lblTK;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pWest;
    private javax.swing.JLabel tilte;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables
}
