/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Utils.SmoothImageLabel;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import javax.swing.JFrame;

/**
 *
 * @author ADMIN
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
public Main() {
    initComponents();
    setTitle("Phần mềm quản lý cửa hàng tiện lợi");
    setExtendedState(JFrame.MAXIMIZED_BOTH);
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        pWest = new javax.swing.JPanel();
        rpWest = new Swing.RoundPanel();
        thongTin = new Swing.RoundPanel();
        anhNV = new Swing.RoundPanel();
        lblAvatar = new javax.swing.JLabel();
        thongtinNV = new Swing.RoundPanel();
        lblName = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jspMenu = new javax.swing.JScrollPane();
        menu = new Swing.RoundPanel();
        btnThongKe = new javax.swing.JButton();
        btnPhieuNhap = new javax.swing.JButton();
        btnNhaCungCap = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnHoaDon = new javax.swing.JButton();
        btnPhieuTra = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnKhachHang = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnNhanVien = new javax.swing.JButton();
        btnTaiKhoan = new javax.swing.JButton();
        nganCach4 = new javax.swing.JSeparator();
        btnDangXuat = new javax.swing.JButton();
        pCenter = new javax.swing.JPanel();
        anhCenter = new SmoothImageLabel("/Icon/resize_output.png") ;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);

        Panel.setBackground(new java.awt.Color(51, 51, 51));
        Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel.setMinimumSize(new java.awt.Dimension(1200, 600));
        Panel.setName(""); // NOI18N
        Panel.setLayout(new java.awt.BorderLayout());

        pWest.setBackground(new java.awt.Color(204, 204, 204));
        pWest.setMinimumSize(new java.awt.Dimension(230, 40));
        pWest.setName("[230, 600]"); // NOI18N
        pWest.setPreferredSize(new java.awt.Dimension(230, 600));
        pWest.setLayout(new java.awt.BorderLayout());

        rpWest.setBackground(new java.awt.Color(204, 204, 204));
        rpWest.setAlignmentX(0.0F);
        rpWest.setAlignmentY(0.0F);
        rpWest.setMinimumSize(new java.awt.Dimension(230, 550));

        thongTin.setBackground(new java.awt.Color(255, 255, 255));
        thongTin.setMinimumSize(new java.awt.Dimension(230, 70));
        thongTin.setPreferredSize(new java.awt.Dimension(230, 70));
        thongTin.setLayout(new java.awt.BorderLayout());

        anhNV.setBackground(new java.awt.Color(255, 255, 255));
        anhNV.setPreferredSize(new java.awt.Dimension(60, 100));
        anhNV.setLayout(new java.awt.GridBagLayout());

        lblAvatar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAvatar.setName(""); // NOI18N
        anhNV.add(lblAvatar, new java.awt.GridBagConstraints());

        thongTin.add(anhNV, java.awt.BorderLayout.LINE_START);

        thongtinNV.setBackground(new java.awt.Color(255, 255, 255));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName.setText("ADMIN");
        lblName.setAlignmentY(0.0F);

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRole.setForeground(new java.awt.Color(102, 102, 102));
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRole.setText("admin");
        lblRole.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout thongtinNVLayout = new javax.swing.GroupLayout(thongtinNV);
        thongtinNV.setLayout(thongtinNVLayout);
        thongtinNVLayout.setHorizontalGroup(
            thongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(thongtinNVLayout.createSequentialGroup()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        thongtinNVLayout.setVerticalGroup(
            thongtinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongtinNVLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        thongTin.add(thongtinNV, java.awt.BorderLayout.CENTER);

        jspMenu.setBorder(null);
        jspMenu.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jspMenu.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jspMenu.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jspMenu.setMinimumSize(new java.awt.Dimension(230, 500));
        jspMenu.setPreferredSize(new java.awt.Dimension(230, 500));

        menu.setBackground(new java.awt.Color(204, 204, 204));
        menu.setAlignmentY(0.0F);
        menu.setMinimumSize(new java.awt.Dimension(230, 500));
        menu.setPreferredSize(new java.awt.Dimension(230, 500));
        menu.setLayout(new javax.swing.BoxLayout(menu, javax.swing.BoxLayout.Y_AXIS));

        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThongKe.setText("Thống Kê");
        btnThongKe.setAlignmentY(0.0F);
        btnThongKe.setBorderPainted(false);
        btnThongKe.setHideActionText(true);
        btnThongKe.setMaximumSize(new java.awt.Dimension(208, 40));
        btnThongKe.setMinimumSize(new java.awt.Dimension(208, 40));
        btnThongKe.setPreferredSize(new java.awt.Dimension(208, 40));
        menu.add(btnThongKe);

        btnPhieuNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPhieuNhap.setText("Phiếu Nhập");
        btnPhieuNhap.setAlignmentY(0.0F);
        btnPhieuNhap.setBorderPainted(false);
        btnPhieuNhap.setMaximumSize(new java.awt.Dimension(208, 40));
        btnPhieuNhap.setMinimumSize(new java.awt.Dimension(208, 40));
        btnPhieuNhap.setPreferredSize(new java.awt.Dimension(208, 40));
        menu.add(btnPhieuNhap);

        btnNhaCungCap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNhaCungCap.setText("Nhà Cung Cấp");
        btnNhaCungCap.setAlignmentY(0.0F);
        btnNhaCungCap.setBorderPainted(false);
        btnNhaCungCap.setMaximumSize(new java.awt.Dimension(208, 40));
        btnNhaCungCap.setMinimumSize(new java.awt.Dimension(208, 40));
        btnNhaCungCap.setPreferredSize(new java.awt.Dimension(208, 40));
        btnNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaCungCapActionPerformed(evt);
            }
        });
        menu.add(btnNhaCungCap);

        btnSanPham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSanPham.setText("Sản Phẩm");
        btnSanPham.setToolTipText("");
        btnSanPham.setAlignmentY(0.0F);
        btnSanPham.setBorderPainted(false);
        btnSanPham.setMaximumSize(new java.awt.Dimension(208, 40));
        btnSanPham.setMinimumSize(new java.awt.Dimension(208, 40));
        btnSanPham.setPreferredSize(new java.awt.Dimension(208, 40));
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });
        menu.add(btnSanPham);

        jSeparator1.setMaximumSize(new java.awt.Dimension(0, 15));
        jSeparator1.setMinimumSize(new java.awt.Dimension(0, 15));
        jSeparator1.setPreferredSize(new java.awt.Dimension(0, 15));
        menu.add(jSeparator1);

        btnHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHoaDon.setText("Hoá Đơn");
        btnHoaDon.setAlignmentY(0.0F);
        btnHoaDon.setBorderPainted(false);
        btnHoaDon.setMaximumSize(new java.awt.Dimension(208, 40));
        btnHoaDon.setMinimumSize(new java.awt.Dimension(208, 40));
        btnHoaDon.setPreferredSize(new java.awt.Dimension(208, 40));
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });
        menu.add(btnHoaDon);

        btnPhieuTra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPhieuTra.setText("Phiếu Trả");
        btnPhieuTra.setAlignmentY(0.0F);
        btnPhieuTra.setBorderPainted(false);
        btnPhieuTra.setMaximumSize(new java.awt.Dimension(208, 40));
        btnPhieuTra.setMinimumSize(new java.awt.Dimension(208, 40));
        btnPhieuTra.setPreferredSize(new java.awt.Dimension(208, 40));
        btnPhieuTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuTraActionPerformed(evt);
            }
        });
        menu.add(btnPhieuTra);
        btnPhieuTra.getAccessibleContext().setAccessibleDescription("");

        jSeparator2.setMaximumSize(new java.awt.Dimension(0, 15));
        jSeparator2.setMinimumSize(new java.awt.Dimension(0, 15));
        jSeparator2.setPreferredSize(new java.awt.Dimension(0, 15));
        menu.add(jSeparator2);

        btnKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKhachHang.setText("Khách Hàng");
        btnKhachHang.setAlignmentY(0.0F);
        btnKhachHang.setBorderPainted(false);
        btnKhachHang.setMaximumSize(new java.awt.Dimension(208, 40));
        btnKhachHang.setMinimumSize(new java.awt.Dimension(208, 40));
        btnKhachHang.setPreferredSize(new java.awt.Dimension(208, 40));
        menu.add(btnKhachHang);
        menu.add(jLabel2);

        btnNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNhanVien.setText("Nhân Viên");
        btnNhanVien.setBorderPainted(false);
        btnNhanVien.setMaximumSize(new java.awt.Dimension(208, 40));
        btnNhanVien.setMinimumSize(new java.awt.Dimension(208, 40));
        btnNhanVien.setPreferredSize(new java.awt.Dimension(208, 40));
        menu.add(btnNhanVien);

        btnTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTaiKhoan.setText("Tài Khoản");
        btnTaiKhoan.setAlignmentY(0.0F);
        btnTaiKhoan.setBorderPainted(false);
        btnTaiKhoan.setMaximumSize(new java.awt.Dimension(208, 40));
        btnTaiKhoan.setMinimumSize(new java.awt.Dimension(208, 40));
        btnTaiKhoan.setPreferredSize(new java.awt.Dimension(208, 40));
        menu.add(btnTaiKhoan);
        menu.add(nganCach4);

        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangXuat.setIcon(new FlatSVGIcon("./icon/logout.svg"));
        btnDangXuat.setText("ĐĂNG XUẤT");
        btnDangXuat.setBorderPainted(false);
        btnDangXuat.setMaximumSize(new java.awt.Dimension(208, 42));
        btnDangXuat.setMinimumSize(new java.awt.Dimension(208, 42));
        btnDangXuat.setPreferredSize(new java.awt.Dimension(208, 42));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        menu.add(btnDangXuat);

        jspMenu.setViewportView(menu);
        menu.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout rpWestLayout = new javax.swing.GroupLayout(rpWest);
        rpWest.setLayout(rpWestLayout);
        rpWestLayout.setHorizontalGroup(
            rpWestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rpWestLayout.createSequentialGroup()
                .addGroup(rpWestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rpWestLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jspMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rpWestLayout.setVerticalGroup(
            rpWestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rpWestLayout.createSequentialGroup()
                .addComponent(thongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
                .addContainerGap())
        );

        pWest.add(rpWest, java.awt.BorderLayout.WEST);

        Panel.add(pWest, java.awt.BorderLayout.LINE_START);

        pCenter.setBackground(new java.awt.Color(0, 51, 51));
        pCenter.setLayout(new java.awt.BorderLayout());

        anhCenter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Icon/resize_output.png"))); // NOI18N
        anhCenter.setMaximumSize(new java.awt.Dimension(1400, 1400));
        anhCenter.setMinimumSize(new java.awt.Dimension(1400, 1400));
        anhCenter.setPreferredSize(new java.awt.Dimension(1400, 1400));
        pCenter.add(anhCenter, java.awt.BorderLayout.CENTER);

        Panel.add(pCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnPhieuTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPhieuTraActionPerformed

    private void btnNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaCungCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhaCungCapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel anhCenter;
    private Swing.RoundPanel anhNV;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnNhaCungCap;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnPhieuNhap;
    private javax.swing.JButton btnPhieuTra;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JScrollPane jspMenu;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRole;
    private Swing.RoundPanel menu;
    private javax.swing.JSeparator nganCach4;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pWest;
    private Swing.RoundPanel rpWest;
    private Swing.RoundPanel thongTin;
    private Swing.RoundPanel thongtinNV;
    // End of variables declaration//GEN-END:variables
}
class BackgroundPanel extends javax.swing.JPanel {
    private java.awt.Image bg;

    public BackgroundPanel(String resourcePath) {
        setOpaque(true);
        java.net.URL url = getClass().getResource(resourcePath);
        if (url == null) throw new IllegalArgumentException("Không tìm thấy ảnh: " + resourcePath);
        bg = new javax.swing.ImageIcon(url).getImage();
    }

    @Override
    protected void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g);
        if (bg == null) return;

        java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
        g2.setRenderingHint(java.awt.RenderingHints.KEY_INTERPOLATION,
                            java.awt.RenderingHints.VALUE_INTERPOLATION_BILINEAR);

        int W = getWidth(), H = getHeight();
        int w = bg.getWidth(null), h = bg.getHeight(null);
        double s = Math.max((double) W / w, (double) H / h); // COVER: phủ kín

        int sw = (int) (w * s), sh = (int) (h * s);
        int x = (W - sw) / 2, y = (H - sh) / 2;

        g2.drawImage(bg, x, y, sw, sh, null);
        g2.dispose();
    }
}

