/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.frame.SanPham;

/**
 *
 * @author ADMIN
 */
public class frmSearchSanPham extends javax.swing.JPanel {

    /**
     * Creates new form frmSearchSanPham
     */
    public frmSearchSanPham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        pNorth = new javax.swing.JPanel();
        northTilte = new javax.swing.JPanel();
        titleName = new javax.swing.JLabel();
        pTimKiem = new javax.swing.JPanel();
        pTimKiem_Row6 = new javax.swing.JPanel();
        pTimKiem_Row1_Col3 = new javax.swing.JPanel();
        lblMaSP = new javax.swing.JLabel();
        pTimKiem_Row1_Col4 = new javax.swing.JPanel();
        txtMaSP = new java.awt.TextField();
        pTimKiem_Row1 = new javax.swing.JPanel();
        pTimKiem_Row1_Col1 = new javax.swing.JPanel();
        lblTenSP = new javax.swing.JLabel();
        pTimKiem_Row1_Col2 = new javax.swing.JPanel();
        txtTenSP = new java.awt.TextField();
        pTimKiem_Row2 = new javax.swing.JPanel();
        pTimKiem_Row2_Col1 = new javax.swing.JPanel();
        lblDanhMuc = new javax.swing.JLabel();
        pTimKiem_Row2_Col2 = new javax.swing.JPanel();
        cboDanhMuc = new javax.swing.JComboBox<>();
        pTimKiem_Row3 = new javax.swing.JPanel();
        pTimKiem_Row3_Col1 = new javax.swing.JPanel();
        lblXuatXu = new javax.swing.JLabel();
        pTimKiem_Row3_Col2 = new javax.swing.JPanel();
        cboXuatXu = new javax.swing.JComboBox<>();
        pTimKiem_Row5 = new javax.swing.JPanel();
        pTimKiem_Row5_Col1 = new javax.swing.JPanel();
        pTimKiem_Row5_Col2 = new javax.swing.JPanel();
        btnTim = new javax.swing.JButton();
        pCenter = new javax.swing.JPanel();
        scrollTableCenter = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        centerTilte = new javax.swing.JPanel();
        titleName1 = new javax.swing.JLabel();
        pSouth = new javax.swing.JPanel();
        btnChiTiet = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        Panel.setName(""); // NOI18N
        Panel.setLayout(new java.awt.BorderLayout());

        pNorth.setBackground(new java.awt.Color(204, 255, 204));
        pNorth.setMinimumSize(new java.awt.Dimension(1200, 250));
        pNorth.setName(""); // NOI18N
        pNorth.setPreferredSize(new java.awt.Dimension(1200, 300));
        pNorth.setLayout(new java.awt.BorderLayout());

        northTilte.setBackground(new java.awt.Color(204, 255, 204));
        northTilte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        northTilte.setMinimumSize(new java.awt.Dimension(1200, 50));
        northTilte.setPreferredSize(new java.awt.Dimension(1200, 50));
        northTilte.setLayout(new java.awt.BorderLayout());

        titleName.setBackground(new java.awt.Color(0, 0, 0));
        titleName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleName.setText("Tìm kiếm sản phẩm");
        titleName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titleName.setMinimumSize(new java.awt.Dimension(1200, 32));
        titleName.setPreferredSize(new java.awt.Dimension(1200, 32));
        northTilte.add(titleName, java.awt.BorderLayout.CENTER);

        pNorth.add(northTilte, java.awt.BorderLayout.PAGE_START);

        pTimKiem.setMinimumSize(new java.awt.Dimension(829, 300));
        pTimKiem.setLayout(new javax.swing.BoxLayout(pTimKiem, javax.swing.BoxLayout.Y_AXIS));

        pTimKiem_Row6.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row6.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row1_Col3.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row1_Col3.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row1_Col3.setLayout(new java.awt.BorderLayout());

        lblMaSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaSP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaSP.setText("Mã sản phẩm:");
        lblMaSP.setAlignmentX(20.0F);
        lblMaSP.setAlignmentY(20.0F);
        pTimKiem_Row1_Col3.add(lblMaSP, java.awt.BorderLayout.CENTER);

        pTimKiem_Row6.add(pTimKiem_Row1_Col3, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row1_Col4.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row1_Col4.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row1_Col4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        txtMaSP.setMaximumSize(new java.awt.Dimension(350, 32));
        txtMaSP.setMinimumSize(new java.awt.Dimension(350, 32));
        txtMaSP.setPreferredSize(new java.awt.Dimension(350, 30));
        pTimKiem_Row1_Col4.add(txtMaSP);

        pTimKiem_Row6.add(pTimKiem_Row1_Col4, java.awt.BorderLayout.CENTER);

        pTimKiem.add(pTimKiem_Row6);

        pTimKiem_Row1.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row1.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row1_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row1_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row1_Col1.setLayout(new java.awt.BorderLayout());

        lblTenSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenSP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTenSP.setText("Tên sản phẩm:");
        lblTenSP.setAlignmentX(20.0F);
        lblTenSP.setAlignmentY(20.0F);
        pTimKiem_Row1_Col1.add(lblTenSP, java.awt.BorderLayout.CENTER);

        pTimKiem_Row1.add(pTimKiem_Row1_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row1_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row1_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row1_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        txtTenSP.setMaximumSize(new java.awt.Dimension(350, 32));
        txtTenSP.setMinimumSize(new java.awt.Dimension(350, 32));
        txtTenSP.setPreferredSize(new java.awt.Dimension(350, 30));
        pTimKiem_Row1_Col2.add(txtTenSP);

        pTimKiem_Row1.add(pTimKiem_Row1_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem.add(pTimKiem_Row1);

        pTimKiem_Row2.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row2.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row2_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row2_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row2_Col1.setLayout(new java.awt.BorderLayout());

        lblDanhMuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDanhMuc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDanhMuc.setText("Danh mục:");
        lblDanhMuc.setAlignmentX(20.0F);
        lblDanhMuc.setAlignmentY(20.0F);
        pTimKiem_Row2_Col1.add(lblDanhMuc, java.awt.BorderLayout.CENTER);

        pTimKiem_Row2.add(pTimKiem_Row2_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row2_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row2_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row2_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        cboDanhMuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDanhMuc.setPreferredSize(new java.awt.Dimension(100, 30));
        cboDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDanhMucActionPerformed(evt);
            }
        });
        pTimKiem_Row2_Col2.add(cboDanhMuc);

        pTimKiem_Row2.add(pTimKiem_Row2_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem.add(pTimKiem_Row2);

        pTimKiem_Row3.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row3.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row3_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row3_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row3_Col1.setLayout(new java.awt.BorderLayout());

        lblXuatXu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblXuatXu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblXuatXu.setText("Xuất xứ:");
        lblXuatXu.setAlignmentX(20.0F);
        lblXuatXu.setAlignmentY(20.0F);
        pTimKiem_Row3_Col1.add(lblXuatXu, java.awt.BorderLayout.CENTER);

        pTimKiem_Row3.add(pTimKiem_Row3_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row3_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row3_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row3_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        cboXuatXu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboXuatXu.setPreferredSize(new java.awt.Dimension(100, 30));
        cboXuatXu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboXuatXuActionPerformed(evt);
            }
        });
        pTimKiem_Row3_Col2.add(cboXuatXu);

        pTimKiem_Row3.add(pTimKiem_Row3_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem.add(pTimKiem_Row3);

        pTimKiem_Row5.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row5.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row5_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row5_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row5_Col1.setLayout(new java.awt.BorderLayout());
        pTimKiem_Row5.add(pTimKiem_Row5_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row5_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row5_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row5_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        btnTim.setBackground(new java.awt.Color(15, 204, 102));
        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTim.setLabel("Tìm kiếm");
        btnTim.setMaximumSize(new java.awt.Dimension(105, 30));
        btnTim.setMinimumSize(new java.awt.Dimension(105, 30));
        btnTim.setPreferredSize(new java.awt.Dimension(105, 30));
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        pTimKiem_Row5_Col2.add(btnTim);

        pTimKiem_Row5.add(pTimKiem_Row5_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem.add(pTimKiem_Row5);

        pNorth.add(pTimKiem, java.awt.BorderLayout.CENTER);

        Panel.add(pNorth, java.awt.BorderLayout.PAGE_START);

        pCenter.setLayout(new java.awt.BorderLayout());

        scrollTableCenter.setMinimumSize(new java.awt.Dimension(1200, 250));
        scrollTableCenter.setPreferredSize(new java.awt.Dimension(1200, 250));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Mô tả", "Danh mục", "Xuất xứ", "ĐVT", "Giá nhập", "Đơn giá", "Tồn kho"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setMinimumSize(new java.awt.Dimension(1200, 250));
        table.setPreferredSize(new java.awt.Dimension(1200, 250));
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowHorizontalLines(true);
        scrollTableCenter.setViewportView(table);

        pCenter.add(scrollTableCenter, java.awt.BorderLayout.CENTER);

        centerTilte.setBackground(new java.awt.Color(204, 255, 204));
        centerTilte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        centerTilte.setMinimumSize(new java.awt.Dimension(1200, 50));
        centerTilte.setPreferredSize(new java.awt.Dimension(1200, 50));
        centerTilte.setLayout(new java.awt.BorderLayout());

        titleName1.setBackground(new java.awt.Color(0, 0, 0));
        titleName1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleName1.setText("Thông tin sản phẩm");
        titleName1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titleName1.setMinimumSize(new java.awt.Dimension(1200, 32));
        titleName1.setPreferredSize(new java.awt.Dimension(1200, 32));
        centerTilte.add(titleName1, java.awt.BorderLayout.CENTER);

        pCenter.add(centerTilte, java.awt.BorderLayout.PAGE_START);

        Panel.add(pCenter, java.awt.BorderLayout.CENTER);

        pSouth.setBackground(new java.awt.Color(222, 222, 222));
        pSouth.setMinimumSize(new java.awt.Dimension(1200, 50));
        pSouth.setPreferredSize(new java.awt.Dimension(1200, 50));

        btnChiTiet.setBackground(new java.awt.Color(15, 204, 102));
        btnChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTiet.setText("Chi tiết");
        btnChiTiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChiTiet.setMaximumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setMinimumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setPreferredSize(new java.awt.Dimension(105, 35));
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });
        pSouth.add(btnChiTiet);

        Panel.add(pSouth, java.awt.BorderLayout.PAGE_END);

        add(Panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChiTietActionPerformed

    private void cboXuatXuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboXuatXuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboXuatXuActionPerformed

    private void cboDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDanhMucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDanhMucActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cboDanhMuc;
    private javax.swing.JComboBox<String> cboXuatXu;
    private javax.swing.JPanel centerTilte;
    private javax.swing.JLabel lblDanhMuc;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblXuatXu;
    private javax.swing.JPanel northTilte;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pNorth;
    private javax.swing.JPanel pSouth;
    private javax.swing.JPanel pTimKiem;
    private javax.swing.JPanel pTimKiem_Row1;
    private javax.swing.JPanel pTimKiem_Row1_Col1;
    private javax.swing.JPanel pTimKiem_Row1_Col2;
    private javax.swing.JPanel pTimKiem_Row1_Col3;
    private javax.swing.JPanel pTimKiem_Row1_Col4;
    private javax.swing.JPanel pTimKiem_Row2;
    private javax.swing.JPanel pTimKiem_Row2_Col1;
    private javax.swing.JPanel pTimKiem_Row2_Col2;
    private javax.swing.JPanel pTimKiem_Row3;
    private javax.swing.JPanel pTimKiem_Row3_Col1;
    private javax.swing.JPanel pTimKiem_Row3_Col2;
    private javax.swing.JPanel pTimKiem_Row5;
    private javax.swing.JPanel pTimKiem_Row5_Col1;
    private javax.swing.JPanel pTimKiem_Row5_Col2;
    private javax.swing.JPanel pTimKiem_Row6;
    private javax.swing.JScrollPane scrollTableCenter;
    private javax.swing.JTable table;
    private javax.swing.JLabel titleName;
    private javax.swing.JLabel titleName1;
    private java.awt.TextField txtMaSP;
    private java.awt.TextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
