/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.frame.PhieuNhap;

import DAO.PhieuNhap.PhieuNhapDAO;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class frmSearchPhieuNhap extends javax.swing.JPanel {
    private final SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
    private final DecimalFormat currencyFormat = new DecimalFormat("#,### VND");

    /**
     * Creates new form frmSeachPhieuNhap
     */
    public frmSearchPhieuNhap() {
        initComponents();
        configureTable();
        loadDataTable();
    }

    private void configureTable() {
        // Ngăn không cho phép người dùng chỉnh sửa bảng
        table.setDefaultEditor(Object.class, null); 

        // Căn giữa cho tất cả các cell trong bảng
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        // Căn giữa cho từng cột
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Ngăn không cho phép chọn nhiều dòng
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

    private void loadDataTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) table.getModel();
        model.setRowCount(0);

        PhieuNhapDAO dao = new PhieuNhapDAO();
        java.util.List<Object[]> list = dao.findAllWithDetails();

        int stt = 1;
        for (Object[] row : list) {
            // row = { maPN, tenNCC, soDienThoai, tenNV, thoiGian(LocalDateTime),
            // tong(BigDecimal) }
            java.time.LocalDateTime ldt = (java.time.LocalDateTime) row[4];
            String ngayNhap = dateFormat.format(java.sql.Timestamp.valueOf(ldt));

            String tongTien = currencyFormat.format((java.math.BigDecimal) row[5]);

            model.addRow(new Object[] {
                    stt++,
                    row[0], // Mã phiếu nhập
                    row[1], // Tên nhà cung cấp
                    row[2], // SĐT NCC
                    row[3], // Tên nhân viên
                    ngayNhap, // Ngày nhập (format)
                    tongTien // Tổng hóa đơn (format)
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        pNorth = new javax.swing.JPanel();
        northTilte = new javax.swing.JPanel();
        titleName = new javax.swing.JLabel();
        pTimKiem = new javax.swing.JPanel();
        pTimKiem_Row1 = new javax.swing.JPanel();
        pTimKiem_Row1_Col1 = new javax.swing.JPanel();
        lblMaPN = new javax.swing.JLabel();
        pTimKiem_Row1_Col2 = new javax.swing.JPanel();
        txtMaPN = new java.awt.TextField();
        pTimKiem_Row2 = new javax.swing.JPanel();
        pTimKiem_Row2_Col1 = new javax.swing.JPanel();
        lblTenNCC = new javax.swing.JLabel();
        pTimKiem_Row2_Col2 = new javax.swing.JPanel();
        txtTenNCC = new java.awt.TextField();
        pTimKiem_Row3 = new javax.swing.JPanel();
        pTimKiem_Row3_Col1 = new javax.swing.JPanel();
        lblSDT = new javax.swing.JLabel();
        pTimKiem_Row3_Col2 = new javax.swing.JPanel();
        txtSDT = new java.awt.TextField();
        pTimKiem_Row4 = new javax.swing.JPanel();
        pTimKiem_Row4_Col1 = new javax.swing.JPanel();
        lblTuNgay = new javax.swing.JLabel();
        pTimKiem_Row4_Col2 = new javax.swing.JPanel();
        dateTuNgay = new com.toedter.calendar.JDateChooser();
        lblDenNgay = new javax.swing.JLabel();
        dateDenNgay = new com.toedter.calendar.JDateChooser();
        pTimKiem_Row5 = new javax.swing.JPanel();
        pTimKiem_Row5_Col1 = new javax.swing.JPanel();
        pTimKiem_Row5_Col2 = new javax.swing.JPanel();
        btnTim = new javax.swing.JButton();
        pCenter = new javax.swing.JPanel();
        centerTilte = new javax.swing.JPanel();
        titleName1 = new javax.swing.JLabel();
        scrollTableCenter = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        pSouth = new javax.swing.JPanel();
        btnChiTiet = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        Panel.setName(""); // NOI18N
        Panel.setLayout(new java.awt.BorderLayout());

        pNorth.setBackground(new java.awt.Color(204, 255, 204));
        pNorth.setMinimumSize(new java.awt.Dimension(1200, 250));
        pNorth.setName(""); // NOI18N
        pNorth.setPreferredSize(new java.awt.Dimension(1200, 250));
        pNorth.setLayout(new java.awt.BorderLayout());

        northTilte.setBackground(new java.awt.Color(204, 255, 204));
        northTilte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        northTilte.setMinimumSize(new java.awt.Dimension(1200, 50));
        northTilte.setPreferredSize(new java.awt.Dimension(1200, 50));
        northTilte.setLayout(new java.awt.BorderLayout());

        titleName.setBackground(new java.awt.Color(0, 0, 0));
        titleName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleName.setText("Tìm kiếm phiếu nhập");
        titleName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titleName.setMinimumSize(new java.awt.Dimension(1200, 32));
        titleName.setPreferredSize(new java.awt.Dimension(1200, 32));
        northTilte.add(titleName, java.awt.BorderLayout.CENTER);

        pNorth.add(northTilte, java.awt.BorderLayout.PAGE_START);

        pTimKiem.setMinimumSize(new java.awt.Dimension(829, 300));
        pTimKiem.setLayout(new javax.swing.BoxLayout(pTimKiem, javax.swing.BoxLayout.Y_AXIS));

        pTimKiem_Row1.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row1.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row1_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row1_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row1_Col1.setLayout(new java.awt.BorderLayout());

        lblMaPN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaPN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaPN.setText("Mã phiếu nhập:");
        lblMaPN.setAlignmentX(20.0F);
        lblMaPN.setAlignmentY(20.0F);
        pTimKiem_Row1_Col1.add(lblMaPN, java.awt.BorderLayout.CENTER);

        pTimKiem_Row1.add(pTimKiem_Row1_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row1_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row1_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row1_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        txtMaPN.setMaximumSize(new java.awt.Dimension(350, 32));
        txtMaPN.setMinimumSize(new java.awt.Dimension(350, 32));
        txtMaPN.setPreferredSize(new java.awt.Dimension(350, 30));
        pTimKiem_Row1_Col2.add(txtMaPN);

        pTimKiem_Row1.add(pTimKiem_Row1_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem.add(pTimKiem_Row1);

        pTimKiem_Row2.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row2.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row2_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row2_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row2_Col1.setLayout(new java.awt.BorderLayout());

        lblTenNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenNCC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTenNCC.setText("Tên nhà cung cấp:");
        lblTenNCC.setAlignmentX(20.0F);
        lblTenNCC.setAlignmentY(20.0F);
        pTimKiem_Row2_Col1.add(lblTenNCC, java.awt.BorderLayout.CENTER);

        pTimKiem_Row2.add(pTimKiem_Row2_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row2_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row2_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row2_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        txtTenNCC.setMaximumSize(new java.awt.Dimension(350, 32));
        txtTenNCC.setMinimumSize(new java.awt.Dimension(350, 32));
        txtTenNCC.setPreferredSize(new java.awt.Dimension(350, 30));
        pTimKiem_Row2_Col2.add(txtTenNCC);

        pTimKiem_Row2.add(pTimKiem_Row2_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem.add(pTimKiem_Row2);

        pTimKiem_Row3.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row3.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row3_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row3_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row3_Col1.setLayout(new java.awt.BorderLayout());

        lblSDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSDT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSDT.setText("Số điện thoại:");
        lblSDT.setAlignmentX(20.0F);
        lblSDT.setAlignmentY(20.0F);
        pTimKiem_Row3_Col1.add(lblSDT, java.awt.BorderLayout.CENTER);

        pTimKiem_Row3.add(pTimKiem_Row3_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row3_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row3_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row3_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        txtSDT.setMaximumSize(new java.awt.Dimension(350, 32));
        txtSDT.setMinimumSize(new java.awt.Dimension(350, 32));
        txtSDT.setPreferredSize(new java.awt.Dimension(350, 30));
        pTimKiem_Row3_Col2.add(txtSDT);

        pTimKiem_Row3.add(pTimKiem_Row3_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem.add(pTimKiem_Row3);

        pTimKiem_Row4.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row4.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row4_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row4_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row4_Col1.setLayout(new java.awt.BorderLayout());

        lblTuNgay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTuNgay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTuNgay.setText("Từ ngày:");
        lblTuNgay.setAlignmentX(20.0F);
        lblTuNgay.setAlignmentY(20.0F);
        pTimKiem_Row4_Col1.add(lblTuNgay, java.awt.BorderLayout.CENTER);

        pTimKiem_Row4.add(pTimKiem_Row4_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row4_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row4_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row4_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        dateTuNgay.setMinimumSize(new java.awt.Dimension(182, 22));
        dateTuNgay.setPreferredSize(new java.awt.Dimension(150, 30));
        pTimKiem_Row4_Col2.add(dateTuNgay);

        lblDenNgay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDenNgay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDenNgay.setText("Đến ngày:");
        lblDenNgay.setAlignmentX(20.0F);
        lblDenNgay.setAlignmentY(20.0F);
        pTimKiem_Row4_Col2.add(lblDenNgay);

        dateDenNgay.setMinimumSize(new java.awt.Dimension(182, 22));
        dateDenNgay.setPreferredSize(new java.awt.Dimension(150, 30));
        pTimKiem_Row4_Col2.add(dateDenNgay);

        pTimKiem_Row4.add(pTimKiem_Row4_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem.add(pTimKiem_Row4);

        pTimKiem_Row5.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row5.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row5_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row5_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row5_Col1.setLayout(new java.awt.BorderLayout());
        pTimKiem_Row5.add(pTimKiem_Row5_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row5_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row5_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row5_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        btnTim.setBackground(new java.awt.Color(15, 204, 102));
        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTim.setLabel("Tìm kiếm");
        btnTim.setMaximumSize(new java.awt.Dimension(105, 30));
        btnTim.setMinimumSize(new java.awt.Dimension(105, 30));
        btnTim.setPreferredSize(new java.awt.Dimension(105, 30));
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        pTimKiem_Row5_Col2.add(btnTim);

        pTimKiem_Row5.add(pTimKiem_Row5_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem.add(pTimKiem_Row5);

        pNorth.add(pTimKiem, java.awt.BorderLayout.CENTER);

        Panel.add(pNorth, java.awt.BorderLayout.PAGE_START);

        pCenter.setLayout(new java.awt.BorderLayout());

        centerTilte.setBackground(new java.awt.Color(204, 255, 204));
        centerTilte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        centerTilte.setMinimumSize(new java.awt.Dimension(1200, 50));
        centerTilte.setPreferredSize(new java.awt.Dimension(1200, 50));
        centerTilte.setLayout(new java.awt.BorderLayout());

        titleName1.setBackground(new java.awt.Color(0, 0, 0));
        titleName1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleName1.setText("Thông tin phiếu nhập");
        titleName1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titleName1.setMinimumSize(new java.awt.Dimension(1200, 32));
        titleName1.setPreferredSize(new java.awt.Dimension(1200, 32));
        centerTilte.add(titleName1, java.awt.BorderLayout.CENTER);

        pCenter.add(centerTilte, java.awt.BorderLayout.PAGE_START);

        scrollTableCenter.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollTableCenter.setMinimumSize(new java.awt.Dimension(1200, 500));
        scrollTableCenter.setPreferredSize(new java.awt.Dimension(1200, 500));

        table.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "STT", "Mã phiếu nhập", "Tên nhà cung cấp", "SĐT", "Tên nhân viên", "Ngày nhập", "Tổng hóa đơn"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        table.setMinimumSize(null);
        table.setName(""); // NOI18N
        table.setPreferredSize(null);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowHorizontalLines(true);
        scrollTableCenter.setViewportView(table);

        pCenter.add(scrollTableCenter, java.awt.BorderLayout.CENTER);

        Panel.add(pCenter, java.awt.BorderLayout.CENTER);

        pSouth.setBackground(new java.awt.Color(222, 222, 222));
        pSouth.setMinimumSize(new java.awt.Dimension(1200, 50));
        pSouth.setPreferredSize(new java.awt.Dimension(1200, 50));

        btnChiTiet.setBackground(new java.awt.Color(15, 204, 102));
        btnChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTiet.setText("Chi tiết");
        btnChiTiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChiTiet.setMaximumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setMinimumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setPreferredSize(new java.awt.Dimension(105, 35));
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });
        pSouth.add(btnChiTiet);

        Panel.add(pSouth, java.awt.BorderLayout.PAGE_END);

        add(Panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String ma = txtMaPN.getText().trim();
        String tenNCC = txtTenNCC.getText().trim();
        String sdt = txtSDT.getText().trim();
        java.util.Date tuNgay = dateTuNgay.getDate();
        java.util.Date denNgay = dateDenNgay.getDate();

        PhieuNhapDAO dao = new PhieuNhapDAO();
        java.util.List<Object[]> list = dao.search(ma, tenNCC, sdt, tuNgay, denNgay);

        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);

        int stt = 1;
        for (Object[] row : list) {
            String ngay = ((LocalDateTime) row[4])
                    .format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"));
            String tongTien = String.format("%,.0f VND", ((java.math.BigDecimal) row[5]));

            model.addRow(new Object[] {
                    stt++,
                    row[0],
                    row[1],
                    row[2],
                    row[3],
                    ngay,
                    tongTien
            });
        }

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Không tìm thấy phiếu nhập phù hợp!",
                    "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }   
    }// GEN-LAST:event_btnTimActionPerformed

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnChiTietActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn một phiếu nhập để xem chi tiết!",
                    "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Giả định cột 0 là STT, cột 1 là Mã hóa đơn
        String maPN = table.getValueAt(row, 1).toString().trim();
        if (maPN.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Không thể xác định mã hóa đơn!",
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Kiểm tra hóa đơn có tồn tại không
        DAO.PhieuNhap.PhieuNhapDAO pnDao = new DAO.PhieuNhap.PhieuNhapDAO();
        Entity.PhieuNhap.PhieuNhap pn = pnDao.findById(maPN).orElse(null);
        if (pn == null) {
            JOptionPane.showMessageDialog(this,
                    "Không tìm thấy phiếu nhập có mã: " + maPN,
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Mở form chi tiết hóa đơn
        javax.swing.JFrame parentFrame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        GUI.form.PhieuNhap.formThongTinPN frm = new GUI.form.PhieuNhap.formThongTinPN(parentFrame, true, pn);
        frm.setLocationRelativeTo(this);
        frm.setVisible(true);
    }// GEN-LAST:event_btnChiTietActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnTim;
    private javax.swing.JPanel centerTilte;
    private com.toedter.calendar.JDateChooser dateDenNgay;
    private com.toedter.calendar.JDateChooser dateTuNgay;
    private javax.swing.JLabel lblDenNgay;
    private javax.swing.JLabel lblMaPN;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTenNCC;
    private javax.swing.JLabel lblTuNgay;
    private javax.swing.JPanel northTilte;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pNorth;
    private javax.swing.JPanel pSouth;
    private javax.swing.JPanel pTimKiem;
    private javax.swing.JPanel pTimKiem_Row1;
    private javax.swing.JPanel pTimKiem_Row1_Col1;
    private javax.swing.JPanel pTimKiem_Row1_Col2;
    private javax.swing.JPanel pTimKiem_Row2;
    private javax.swing.JPanel pTimKiem_Row2_Col1;
    private javax.swing.JPanel pTimKiem_Row2_Col2;
    private javax.swing.JPanel pTimKiem_Row3;
    private javax.swing.JPanel pTimKiem_Row3_Col1;
    private javax.swing.JPanel pTimKiem_Row3_Col2;
    private javax.swing.JPanel pTimKiem_Row4;
    private javax.swing.JPanel pTimKiem_Row4_Col1;
    private javax.swing.JPanel pTimKiem_Row4_Col2;
    private javax.swing.JPanel pTimKiem_Row5;
    private javax.swing.JPanel pTimKiem_Row5_Col1;
    private javax.swing.JPanel pTimKiem_Row5_Col2;
    private javax.swing.JScrollPane scrollTableCenter;
    private javax.swing.JTable table;
    private javax.swing.JLabel titleName;
    private javax.swing.JLabel titleName1;
    private java.awt.TextField txtMaPN;
    private java.awt.TextField txtSDT;
    private java.awt.TextField txtTenNCC;
    // End of variables declaration//GEN-END:variables
}
