/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.form.NhaCungCap;

import Entity.PhieuNhap.NhaCungCap;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author ADMIN
 */
public class formThongTinNCC extends javax.swing.JDialog {

    /**
     * Creates new form formThongTinNCC
     * @param parent
     * @param modal
     * @param ncc
     */
    public formThongTinNCC(java.awt.Frame parent, boolean modal, NhaCungCap ncc) {
        super(parent, modal);
        initComponents();
        configureTable();
        disableTextFieldFocus();
        setThongTinNCC(ncc);
    }

    private void configureTable() {
        // Căn giữa cho tất cả các cell trong bảng
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        // Căn giữa cho từng cột
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Ngăn không cho phép chọn nhiều dòng
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setRowSelectionAllowed(true);
        table.setColumnSelectionAllowed(false);
    }

    private void setThongTinNCC(Entity.PhieuNhap.NhaCungCap ncc) {
        if (ncc == null)
            return;
        txtMa.setText(ncc.getMaNCC());
        txtHoTen.setText(ncc.getTenNCC());
        txtSDT.setText(ncc.getSdt());
        txtDiaChi.setText(ncc.getDiaChiNCC());
        loadPhieuNhapTheoNCC(ncc.getMaNCC());
    }

    private void disableTextFieldFocus() {
        txtMa.setEditable(false);
        txtMa.setFocusable(false);

        txtHoTen.setEditable(false);
        txtHoTen.setFocusable(false);

        txtSDT.setEditable(false);
        txtSDT.setFocusable(false);

        txtDiaChi.setEditable(false);
        txtDiaChi.setFocusable(false);
    }

    private void loadPhieuNhapTheoNCC(String maNCC) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) table.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ trong bảng

        DAO.PhieuNhap.PhieuNhapDAO dao = new DAO.PhieuNhap.PhieuNhapDAO();
        java.util.List<Object[]> list = dao.findByMaNCC(maNCC);

        int stt = 1;
        java.text.DecimalFormat df = new java.text.DecimalFormat("#,##0 VNĐ");
        java.time.format.DateTimeFormatter dtf = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

        for (Object[] row : list) {
            String maPN = (String) row[0];
            String tenNV = (String) row[1];
            java.time.LocalDateTime thoiGian = (java.time.LocalDateTime) row[2];
            double tongTien = (double) row[3];

            model.addRow(new Object[] {
                    stt++,
                    maPN,
                    tenNV,
                    thoiGian != null ? dtf.format(thoiGian) : "",
                    df.format(tongTien)
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel = new Swing.RoundPanel();
        pNorth = new javax.swing.JPanel();
        lblThemKH = new javax.swing.JLabel();
        pCenter = new javax.swing.JPanel();
        pThongTin = new javax.swing.JPanel();
        lblMa = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        lblTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lblDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        pTilteTable = new javax.swing.JPanel();
        tilteTable = new javax.swing.JLabel();
        scrollTableCenter = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        pSouth = new javax.swing.JPanel();
        btnHuy = new javax.swing.JButton();
        btnChiTiet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 600));

        roundPanel.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel.setMaximumSize(new java.awt.Dimension(600, 600));
        roundPanel.setMinimumSize(new java.awt.Dimension(600, 600));
        roundPanel.setName(""); // NOI18N
        roundPanel.setPreferredSize(new java.awt.Dimension(600, 600));
        roundPanel.setLayout(new java.awt.BorderLayout());

        pNorth.setBackground(new java.awt.Color(204, 255, 204));
        pNorth.setMaximumSize(new java.awt.Dimension(600, 50));
        pNorth.setMinimumSize(new java.awt.Dimension(600, 50));
        pNorth.setPreferredSize(new java.awt.Dimension(600, 50));
        pNorth.setLayout(new java.awt.BorderLayout());

        lblThemKH.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblThemKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThemKH.setText(" Thông tin nhà cung cấp");
        lblThemKH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblThemKH.setMaximumSize(new java.awt.Dimension(600, 50));
        lblThemKH.setMinimumSize(new java.awt.Dimension(600, 50));
        lblThemKH.setPreferredSize(new java.awt.Dimension(600, 50));
        pNorth.add(lblThemKH, java.awt.BorderLayout.CENTER);

        roundPanel.add(pNorth, java.awt.BorderLayout.PAGE_START);

        pCenter.setBackground(new java.awt.Color(255, 255, 255));
        pCenter.setMaximumSize(new java.awt.Dimension(600, 300));
        pCenter.setMinimumSize(new java.awt.Dimension(600, 300));
        pCenter.setPreferredSize(new java.awt.Dimension(600, 300));

        pThongTin.setBackground(new java.awt.Color(255, 255, 255));
        pThongTin.setMaximumSize(new java.awt.Dimension(550, 150));
        pThongTin.setMinimumSize(new java.awt.Dimension(550, 150));
        pThongTin.setPreferredSize(new java.awt.Dimension(550, 150));
        pThongTin.setLayout(new java.awt.GridLayout(5, 2, 5, 0));

        lblMa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMa.setText("Mã nhà cung cấp:");
        lblMa.setAlignmentX(20.0F);
        lblMa.setAlignmentY(20.0F);
        pThongTin.add(lblMa);

        txtMa.setEditable(false);
        txtMa.setPreferredSize(new java.awt.Dimension(350, 22));
        pThongTin.add(txtMa);

        lblTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTen.setText("Tên nhà cung cấp:");
        lblTen.setAlignmentX(20.0F);
        lblTen.setAlignmentY(20.0F);
        pThongTin.add(lblTen);

        txtHoTen.setEditable(false);
        txtHoTen.setPreferredSize(new java.awt.Dimension(350, 22));
        pThongTin.add(txtHoTen);

        lblSDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSDT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSDT.setText("SĐT:");
        pThongTin.add(lblSDT);

        txtSDT.setEditable(false);
        txtSDT.setPreferredSize(new java.awt.Dimension(350, 22));
        pThongTin.add(txtSDT);

        lblDiaChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDiaChi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiaChi.setText("Địa chỉ:");
        pThongTin.add(lblDiaChi);

        txtDiaChi.setEditable(false);
        txtDiaChi.setPreferredSize(new java.awt.Dimension(350, 22));
        pThongTin.add(txtDiaChi);

        pCenter.add(pThongTin);

        pTilteTable.setMinimumSize(new java.awt.Dimension(550, 40));
        pTilteTable.setPreferredSize(new java.awt.Dimension(550, 40));

        tilteTable.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tilteTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tilteTable.setText("Lịch sử giao dịch");
        tilteTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tilteTable.setMaximumSize(new java.awt.Dimension(600, 40));
        tilteTable.setMinimumSize(new java.awt.Dimension(600, 40));
        tilteTable.setPreferredSize(new java.awt.Dimension(600, 40));
        pTilteTable.add(tilteTable);

        pCenter.add(pTilteTable);

        scrollTableCenter.setMinimumSize(new java.awt.Dimension(550, 280));
        scrollTableCenter.setPreferredSize(new java.awt.Dimension(550, 280));

        table.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "STT", "Mã phiếu nhập", "Tên nhân viên", "Ngày nhập", "Tổng hóa đơn"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        table.setName(""); // NOI18N
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowHorizontalLines(true);
        scrollTableCenter.setViewportView(table);

        pCenter.add(scrollTableCenter);

        roundPanel.add(pCenter, java.awt.BorderLayout.CENTER);

        pSouth.setBackground(new java.awt.Color(255, 255, 255));
        pSouth.setMaximumSize(new java.awt.Dimension(600, 50));
        pSouth.setMinimumSize(new java.awt.Dimension(600, 50));
        pSouth.setPreferredSize(new java.awt.Dimension(600, 50));

        btnHuy.setBackground(new java.awt.Color(255, 103, 102));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Huỷ");
        btnHuy.setPreferredSize(new java.awt.Dimension(90, 35));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        pSouth.add(btnHuy);

        btnChiTiet.setBackground(new java.awt.Color(15, 204, 102));
        btnChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTiet.setText("Chi tiết");
        btnChiTiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChiTiet.setMaximumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setMinimumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setPreferredSize(new java.awt.Dimension(90, 35));
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });
        pSouth.add(btnChiTiet);

        roundPanel.add(pSouth, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(roundPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnChiTietActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        System.out.println("Selected row: " + row);
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một phiếu nhập để xem chi tiết!", "Thông báo",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String maPN = table.getValueAt(row, 1).toString().trim();
        System.out.println("Selected maPN: " + maPN);

        if (maPN.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Không thể xác định mã phiếu nhập!",
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Kiểm tra hóa đơn có tồn tại không
        DAO.PhieuNhap.PhieuNhapDAO pnDao = new DAO.PhieuNhap.PhieuNhapDAO();
        Entity.PhieuNhap.PhieuNhap pn = pnDao.findById(maPN).orElse(null);
        if (pn == null) {
            JOptionPane.showMessageDialog(this,
                    "Không tìm thấy phiếu nhập có mã: " + maPN,
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Mở form chi tiết hóa đơn
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame frameParent = parentWindow instanceof java.awt.Frame ? (java.awt.Frame) parentWindow : null;

        // Tạo dialog modal, liên kết với parent đúng
        GUI.form.PhieuNhap.formThongTinPN frm = new GUI.form.PhieuNhap.formThongTinPN(frameParent, false, pn);
        frm.setLocationRelativeTo(parentWindow);

        // (Tùy chọn) luôn ở trên để chắc chắn
        frm.setAlwaysOnTop(true);

        frm.setVisible(true);
    }// GEN-LAST:event_btnChiTietActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        dispose();
    }// GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
//        // (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
//         * look and feel.
//         * For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(formThongTinNCC.class.getName()).log(java.util.logging.Level.SEVERE,
//                    null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(formThongTinNCC.class.getName()).log(java.util.logging.Level.SEVERE,
//                    null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(formThongTinNCC.class.getName()).log(java.util.logging.Level.SEVERE,
//                    null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(formThongTinNCC.class.getName()).log(java.util.logging.Level.SEVERE,
//                    null, ex);
//        }
//        // </editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                formThongTinNCC dialog = new formThongTinNCC(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnHuy;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblThemKH;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pNorth;
    private javax.swing.JPanel pSouth;
    private javax.swing.JPanel pThongTin;
    private javax.swing.JPanel pTilteTable;
    private Swing.RoundPanel roundPanel;
    private javax.swing.JScrollPane scrollTableCenter;
    private javax.swing.JTable table;
    private javax.swing.JLabel tilteTable;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
