/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.frame.HoaDon;

import DAO.HoaDon.HoaDonDAO;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class frmSearchHoaDon extends javax.swing.JPanel {
    private final SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
    private final DecimalFormat currencyFormat = new DecimalFormat("#,### VND");

    /**
     * Creates new form frmSearchHoaDon
     */
    public frmSearchHoaDon() {
        initComponents();
        configureTable();
        loadDataTable();
    }

    private void configureTable() {
        // Ngăn không cho phép người dùng chỉnh sửa bảng
        table.setDefaultEditor(Object.class, null); 
                                                    
        // Căn giữa cho tất cả các cell trong bảng
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        // Căn giữa cho từng cột
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Ngăn không cho phép chọn nhiều dòng
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

    private void loadDataTable() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);

        HoaDonDAO dao = new HoaDonDAO();
        List<Object[]> list = dao.findAllWithDetails();

        int stt = 1;
        for (Object[] row : list) {
            // row[3] là LocalDateTime (có thể null nếu DB trống)
            String ngayMua = "";
            if (row[3] != null) {
                LocalDateTime ldt = (LocalDateTime) row[3];
                ngayMua = dateFormat.format(java.sql.Timestamp.valueOf(ldt));
            }

            // Tiền tệ: tổng hóa đơn (vì không còn giảm giá)
            String tongTienStr = currencyFormat.format(row[6]); // tổng tiền = row[6]

            model.addRow(new Object[] {
                    stt++, // 0: STT
                    row[0], // 1: Mã HD
                    row[1], // 2: Tên KH
                    row[2], // 3: SĐT
                    row[4], // 4: Tên NV
                    ngayMua, // 5: Ngày mua
                    row[7], // 6: Kiểu thanh toán
                    tongTienStr // 7: Tổng tiền (hiển thị sau kiểu thanh toán)
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        pNorth = new javax.swing.JPanel();
        northTilte = new javax.swing.JPanel();
        titleName = new javax.swing.JLabel();
        pTimKiem1 = new javax.swing.JPanel();
        pTimKiem_Row1 = new javax.swing.JPanel();
        pTimKiem_Row1_Col1 = new javax.swing.JPanel();
        lblMaHD = new javax.swing.JLabel();
        pTimKiem_Row1_Col2 = new javax.swing.JPanel();
        txtMaHD = new java.awt.TextField();
        pTimKiem_Row2 = new javax.swing.JPanel();
        pTimKiem_Row2_Col1 = new javax.swing.JPanel();
        lblTenKH = new javax.swing.JLabel();
        pTimKiem_Row2_Col2 = new javax.swing.JPanel();
        txtTenKH = new java.awt.TextField();
        pTimKiem_Row3 = new javax.swing.JPanel();
        pTimKiem_Row3_Col1 = new javax.swing.JPanel();
        lblSDT = new javax.swing.JLabel();
        pTimKiem_Row3_Col2 = new javax.swing.JPanel();
        txtSDT = new java.awt.TextField();
        pTimKiem_Row4 = new javax.swing.JPanel();
        pTimKiem_Row4_Col1 = new javax.swing.JPanel();
        lblTuNgay = new javax.swing.JLabel();
        pTimKiem_Row4_Col2 = new javax.swing.JPanel();
        dateTuNgay = new com.toedter.calendar.JDateChooser();
        lblDenNgay = new javax.swing.JLabel();
        dateDenNgay = new com.toedter.calendar.JDateChooser();
        pTimKiem_Row5 = new javax.swing.JPanel();
        pTimKiem_Row5_Col1 = new javax.swing.JPanel();
        pTimKiem_Row5_Col2 = new javax.swing.JPanel();
        btnTim = new javax.swing.JButton();
        pCenter = new javax.swing.JPanel();
        centerTilte = new javax.swing.JPanel();
        titleName1 = new javax.swing.JLabel();
        scrollTableCenter = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        pSouth = new javax.swing.JPanel();
        btnChiTiet = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setLayout(new java.awt.BorderLayout());

        Panel.setName(""); // NOI18N
        Panel.setLayout(new java.awt.BorderLayout());

        pNorth.setBackground(new java.awt.Color(204, 255, 204));
        pNorth.setMinimumSize(new java.awt.Dimension(1200, 250));
        pNorth.setName(""); // NOI18N
        pNorth.setPreferredSize(new java.awt.Dimension(1200, 250));
        pNorth.setLayout(new java.awt.BorderLayout());

        northTilte.setBackground(new java.awt.Color(204, 255, 204));
        northTilte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        northTilte.setMinimumSize(new java.awt.Dimension(1200, 50));
        northTilte.setPreferredSize(new java.awt.Dimension(1200, 50));
        northTilte.setLayout(new java.awt.BorderLayout());

        titleName.setBackground(new java.awt.Color(0, 0, 0));
        titleName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleName.setText("Tìm kiếm hóa đơn");
        titleName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titleName.setMinimumSize(new java.awt.Dimension(1200, 32));
        titleName.setPreferredSize(new java.awt.Dimension(1200, 32));
        northTilte.add(titleName, java.awt.BorderLayout.CENTER);

        pNorth.add(northTilte, java.awt.BorderLayout.PAGE_START);

        pTimKiem1.setMinimumSize(new java.awt.Dimension(829, 300));
        pTimKiem1.setLayout(new javax.swing.BoxLayout(pTimKiem1, javax.swing.BoxLayout.Y_AXIS));

        pTimKiem_Row1.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row1.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row1_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row1_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row1_Col1.setLayout(new java.awt.BorderLayout());

        lblMaHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaHD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaHD.setText("Mã hóa đơn:");
        lblMaHD.setAlignmentX(20.0F);
        lblMaHD.setAlignmentY(20.0F);
        pTimKiem_Row1_Col1.add(lblMaHD, java.awt.BorderLayout.CENTER);

        pTimKiem_Row1.add(pTimKiem_Row1_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row1_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row1_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row1_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        txtMaHD.setMaximumSize(new java.awt.Dimension(350, 32));
        txtMaHD.setMinimumSize(new java.awt.Dimension(350, 32));
        txtMaHD.setPreferredSize(new java.awt.Dimension(350, 30));
        pTimKiem_Row1_Col2.add(txtMaHD);

        pTimKiem_Row1.add(pTimKiem_Row1_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem1.add(pTimKiem_Row1);

        pTimKiem_Row2.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row2.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row2_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row2_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row2_Col1.setLayout(new java.awt.BorderLayout());

        lblTenKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenKH.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTenKH.setText("Tên khách hàng:");
        lblTenKH.setAlignmentX(20.0F);
        lblTenKH.setAlignmentY(20.0F);
        pTimKiem_Row2_Col1.add(lblTenKH, java.awt.BorderLayout.CENTER);

        pTimKiem_Row2.add(pTimKiem_Row2_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row2_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row2_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row2_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        txtTenKH.setMaximumSize(new java.awt.Dimension(350, 32));
        txtTenKH.setMinimumSize(new java.awt.Dimension(350, 32));
        txtTenKH.setPreferredSize(new java.awt.Dimension(350, 30));
        pTimKiem_Row2_Col2.add(txtTenKH);

        pTimKiem_Row2.add(pTimKiem_Row2_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem1.add(pTimKiem_Row2);

        pTimKiem_Row3.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row3.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row3_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row3_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row3_Col1.setLayout(new java.awt.BorderLayout());

        lblSDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSDT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSDT.setText("Số điện thoại:");
        lblSDT.setAlignmentX(20.0F);
        lblSDT.setAlignmentY(20.0F);
        pTimKiem_Row3_Col1.add(lblSDT, java.awt.BorderLayout.CENTER);

        pTimKiem_Row3.add(pTimKiem_Row3_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row3_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row3_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row3_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        txtSDT.setMaximumSize(new java.awt.Dimension(350, 32));
        txtSDT.setMinimumSize(new java.awt.Dimension(350, 32));
        txtSDT.setPreferredSize(new java.awt.Dimension(350, 30));
        pTimKiem_Row3_Col2.add(txtSDT);

        pTimKiem_Row3.add(pTimKiem_Row3_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem1.add(pTimKiem_Row3);

        pTimKiem_Row4.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row4.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row4_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row4_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row4_Col1.setLayout(new java.awt.BorderLayout());

        lblTuNgay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTuNgay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTuNgay.setText("Từ ngày:");
        lblTuNgay.setAlignmentX(20.0F);
        lblTuNgay.setAlignmentY(20.0F);
        pTimKiem_Row4_Col1.add(lblTuNgay, java.awt.BorderLayout.CENTER);

        pTimKiem_Row4.add(pTimKiem_Row4_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row4_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row4_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row4_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        dateTuNgay.setMinimumSize(new java.awt.Dimension(182, 22));
        dateTuNgay.setPreferredSize(new java.awt.Dimension(150, 30));
        pTimKiem_Row4_Col2.add(dateTuNgay);

        lblDenNgay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDenNgay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDenNgay.setText("Đến ngày:");
        lblDenNgay.setAlignmentX(20.0F);
        lblDenNgay.setAlignmentY(20.0F);
        pTimKiem_Row4_Col2.add(lblDenNgay);

        dateDenNgay.setMinimumSize(new java.awt.Dimension(182, 22));
        dateDenNgay.setPreferredSize(new java.awt.Dimension(150, 30));
        pTimKiem_Row4_Col2.add(dateDenNgay);

        pTimKiem_Row4.add(pTimKiem_Row4_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem1.add(pTimKiem_Row4);

        pTimKiem_Row5.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row5.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row5_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row5_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row5_Col1.setLayout(new java.awt.BorderLayout());
        pTimKiem_Row5.add(pTimKiem_Row5_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row5_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row5_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row5_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        btnTim.setBackground(new java.awt.Color(15, 204, 102));
        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTim.setLabel("Tìm kiếm");
        btnTim.setMaximumSize(new java.awt.Dimension(105, 30));
        btnTim.setMinimumSize(new java.awt.Dimension(105, 30));
        btnTim.setPreferredSize(new java.awt.Dimension(105, 30));
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        pTimKiem_Row5_Col2.add(btnTim);

        pTimKiem_Row5.add(pTimKiem_Row5_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem1.add(pTimKiem_Row5);

        pNorth.add(pTimKiem1, java.awt.BorderLayout.CENTER);

        Panel.add(pNorth, java.awt.BorderLayout.PAGE_START);

        pCenter.setMinimumSize(new java.awt.Dimension(1200, 300));
        pCenter.setPreferredSize(new java.awt.Dimension(1200, 300));
        pCenter.setLayout(new java.awt.BorderLayout());

        centerTilte.setBackground(new java.awt.Color(204, 255, 204));
        centerTilte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        centerTilte.setMinimumSize(new java.awt.Dimension(1200, 50));
        centerTilte.setPreferredSize(new java.awt.Dimension(1200, 50));
        centerTilte.setLayout(new java.awt.BorderLayout());

        titleName1.setBackground(new java.awt.Color(0, 0, 0));
        titleName1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleName1.setText("Thông tin hóa đơn");
        titleName1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titleName1.setMinimumSize(new java.awt.Dimension(1200, 32));
        titleName1.setPreferredSize(new java.awt.Dimension(1200, 32));
        centerTilte.add(titleName1, java.awt.BorderLayout.CENTER);

        pCenter.add(centerTilte, java.awt.BorderLayout.PAGE_START);

        scrollTableCenter.setMinimumSize(new java.awt.Dimension(1200, 500));

        table.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "STT", "Mã hóa đơn", "Tên khách hàng", "SĐT", "Tên nhân viên", "Ngày mua", "Kiểu thanh toán",
                        "Tổng hóa đơn"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        table.setMinimumSize(null);
        table.setPreferredSize(null);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowHorizontalLines(true);
        scrollTableCenter.setViewportView(table);

        pCenter.add(scrollTableCenter, java.awt.BorderLayout.CENTER);

        Panel.add(pCenter, java.awt.BorderLayout.CENTER);

        pSouth.setBackground(new java.awt.Color(222, 222, 222));
        pSouth.setMinimumSize(new java.awt.Dimension(1200, 50));
        pSouth.setPreferredSize(new java.awt.Dimension(1200, 50));

        btnChiTiet.setBackground(new java.awt.Color(15, 204, 102));
        btnChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTiet.setText("Chi tiết");
        btnChiTiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChiTiet.setMaximumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setMinimumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setPreferredSize(new java.awt.Dimension(105, 35));
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });
        pSouth.add(btnChiTiet);

        Panel.add(pSouth, java.awt.BorderLayout.PAGE_END);

        add(Panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnChiTietActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn một hóa đơn để xem chi tiết!",
                    "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Giả định cột 0 là STT, cột 1 là Mã hóa đơn
        String maHD = table.getValueAt(row, 1).toString().trim();
        if (maHD.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Không thể xác định mã hóa đơn!",
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Kiểm tra hóa đơn có tồn tại không
        DAO.HoaDon.HoaDonDAO hdDao = new DAO.HoaDon.HoaDonDAO();
        Entity.HoaDon.HoaDon hd = hdDao.findById(maHD).orElse(null);
        if (hd == null) {
            JOptionPane.showMessageDialog(this,
                    "Không tìm thấy hóa đơn có mã: " + maHD,
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Mở form chi tiết hóa đơn
        javax.swing.JFrame parentFrame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        GUI.form.HoaDon.formThongTinHD frm = new GUI.form.HoaDon.formThongTinHD(parentFrame, true, hd);
        frm.setLocationRelativeTo(this);
        frm.setVisible(true);
    }// GEN-LAST:event_btnChiTietActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String ma = txtMaHD.getText().trim();
        String tenKH = txtTenKH.getText().trim();
        String sdt = txtSDT.getText().trim();
        java.util.Date tuNgay = dateTuNgay.getDate();
        java.util.Date denNgay = dateDenNgay.getDate();

        HoaDonDAO dao = new HoaDonDAO();
        List<Object[]> list = dao.search(ma, tenKH, sdt, tuNgay, denNgay);

        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);

        int stt = 1;
        for (Object[] row : list) {
            LocalDateTime ngay = (LocalDateTime) row[3];
            String ngayMua = ngay.format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"));
            String tongTien = String.format("%,.0f VND", ((java.math.BigDecimal) row[5]));

            model.addRow(new Object[] {
                    stt++, // STT
                    row[0], // Mã hóa đơn
                    row[1], // Tên khách hàng
                    row[2], // SĐT
                    row[4], // Tên nhân viên
                    ngayMua, // Ngày mua
                    row[6], // Kiểu thanh toán
                    tongTien // Tổng tiền
            });
        }

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Không tìm thấy hóa đơn phù hợp!",
                    "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }// GEN-LAST:event_btnTimActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnTim;
    private javax.swing.JPanel centerTilte;
    private com.toedter.calendar.JDateChooser dateDenNgay;
    private com.toedter.calendar.JDateChooser dateTuNgay;
    private javax.swing.JLabel lblDenNgay;
    private javax.swing.JLabel lblMaHD;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTenKH;
    private javax.swing.JLabel lblTuNgay;
    private javax.swing.JPanel northTilte;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pNorth;
    private javax.swing.JPanel pSouth;
    private javax.swing.JPanel pTimKiem1;
    private javax.swing.JPanel pTimKiem_Row1;
    private javax.swing.JPanel pTimKiem_Row1_Col1;
    private javax.swing.JPanel pTimKiem_Row1_Col2;
    private javax.swing.JPanel pTimKiem_Row2;
    private javax.swing.JPanel pTimKiem_Row2_Col1;
    private javax.swing.JPanel pTimKiem_Row2_Col2;
    private javax.swing.JPanel pTimKiem_Row3;
    private javax.swing.JPanel pTimKiem_Row3_Col1;
    private javax.swing.JPanel pTimKiem_Row3_Col2;
    private javax.swing.JPanel pTimKiem_Row4;
    private javax.swing.JPanel pTimKiem_Row4_Col1;
    private javax.swing.JPanel pTimKiem_Row4_Col2;
    private javax.swing.JPanel pTimKiem_Row5;
    private javax.swing.JPanel pTimKiem_Row5_Col1;
    private javax.swing.JPanel pTimKiem_Row5_Col2;
    private javax.swing.JScrollPane scrollTableCenter;
    private javax.swing.JTable table;
    private javax.swing.JLabel titleName;
    private javax.swing.JLabel titleName1;
    private java.awt.TextField txtMaHD;
    private java.awt.TextField txtSDT;
    private java.awt.TextField txtTenKH;
    // End of variables declaration//GEN-END:variables
}
