/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.form.PhieuXuat;

import com.formdev.flatlaf.extras.FlatSVGIcon;

/**
 *
 * @author ADMIN
 */
public class formThongTinPX extends javax.swing.JDialog {

    /**
     * Creates new form formThongTinPX
     */
    public formThongTinPX(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pNorth = new javax.swing.JPanel();
        pTilte = new javax.swing.JPanel();
        titleNorth = new javax.swing.JLabel();
        pThongTinHD = new javax.swing.JPanel();
        pMaHD = new javax.swing.JPanel();
        jMaHD = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        pTenKH = new javax.swing.JPanel();
        jTenKH = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        pTenNV = new javax.swing.JPanel();
        lblTenNV = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        pCenter = new javax.swing.JPanel();
        pAnh = new javax.swing.JPanel();
        anhSP = new javax.swing.JPanel();
        lblAnhSP = new javax.swing.JLabel();
        tableSP = new javax.swing.JPanel();
        spTableSP = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        pTongHD = new javax.swing.JPanel();
        pTongHoaDon = new javax.swing.JPanel();
        lblTongHD = new javax.swing.JLabel();
        txtTong = new javax.swing.JTextField();
        pTitleCenter = new javax.swing.JPanel();
        lblThuoc = new javax.swing.JLabel();
        pSouth = new javax.swing.JPanel();
        btnHuy = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 600));

        pNorth.setBackground(new java.awt.Color(204, 255, 204));
        pNorth.setLayout(new java.awt.BorderLayout());

        pTilte.setBackground(new java.awt.Color(204, 255, 204));
        pTilte.setMinimumSize(new java.awt.Dimension(1200, 50));

        titleNorth.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        titleNorth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleNorth.setText("CHI TIẾT HÓA ĐƠN");
        titleNorth.setPreferredSize(new java.awt.Dimension(149, 40));

        javax.swing.GroupLayout pTilteLayout = new javax.swing.GroupLayout(pTilte);
        pTilte.setLayout(pTilteLayout);
        pTilteLayout.setHorizontalGroup(
            pTilteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pTilteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pTilteLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(titleNorth, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pTilteLayout.setVerticalGroup(
            pTilteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pTilteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pTilteLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(titleNorth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pNorth.add(pTilte, java.awt.BorderLayout.PAGE_START);

        pThongTinHD.setBackground(new java.awt.Color(255, 255, 255));
        pThongTinHD.setMinimumSize(new java.awt.Dimension(1200, 70));
        pThongTinHD.setPreferredSize(new java.awt.Dimension(1200, 70));
        pThongTinHD.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 16));

        pMaHD.setBackground(new java.awt.Color(255, 255, 255));
        pMaHD.setPreferredSize(new java.awt.Dimension(340, 40));
        pMaHD.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jMaHD.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jMaHD.setText("Mã hóa đơn ");
        jMaHD.setPreferredSize(new java.awt.Dimension(120, 40));
        pMaHD.add(jMaHD);

        txtMaHD.setEditable(false);
        txtMaHD.setFont(new java.awt.Font("Roboto Mono", 1, 14)); // NOI18N
        txtMaHD.setText("Z2NX8CN1A");
        txtMaHD.setFocusable(false);
        txtMaHD.setPreferredSize(new java.awt.Dimension(200, 40));
        pMaHD.add(txtMaHD);

        pThongTinHD.add(pMaHD);

        pTenKH.setBackground(new java.awt.Color(255, 255, 255));
        pTenKH.setPreferredSize(new java.awt.Dimension(440, 40));
        pTenKH.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jTenKH.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTenKH.setText("Tên khách hàng");
        jTenKH.setPreferredSize(new java.awt.Dimension(120, 40));
        pTenKH.add(jTenKH);

        txtTenKH.setEditable(false);
        txtTenKH.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTenKH.setText("Nguyễn Văn A");
        txtTenKH.setFocusable(false);
        txtTenKH.setPreferredSize(new java.awt.Dimension(300, 40));
        pTenKH.add(txtTenKH);

        pThongTinHD.add(pTenKH);

        pTenNV.setBackground(new java.awt.Color(255, 255, 255));
        pTenNV.setPreferredSize(new java.awt.Dimension(340, 40));
        pTenNV.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        lblTenNV.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblTenNV.setText("Tên nhân viên");
        lblTenNV.setPreferredSize(new java.awt.Dimension(120, 40));
        pTenNV.add(lblTenNV);

        txtTenNV.setEditable(false);
        txtTenNV.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTenNV.setText("Vũ Nương");
        txtTenNV.setFocusable(false);
        txtTenNV.setPreferredSize(new java.awt.Dimension(200, 40));
        pTenNV.add(txtTenNV);

        pThongTinHD.add(pTenNV);

        pNorth.add(pThongTinHD, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pNorth, java.awt.BorderLayout.NORTH);

        pCenter.setBackground(new java.awt.Color(255, 255, 255));
        pCenter.setPreferredSize(new java.awt.Dimension(1200, 500));
        pCenter.setLayout(new java.awt.BorderLayout());

        pAnh.setBackground(new java.awt.Color(255, 255, 255));
        pAnh.setPreferredSize(new java.awt.Dimension(400, 100));

        anhSP.setBackground(new java.awt.Color(255, 255, 255));
        anhSP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(237, 237, 237), 2, true));
        anhSP.setPreferredSize(new java.awt.Dimension(300, 300));
        anhSP.setLayout(new java.awt.BorderLayout());

        lblAnhSP.setBackground(new java.awt.Color(255, 255, 255));
        lblAnhSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnhSP.setIcon(new FlatSVGIcon("./icon/image.svg"));
        lblAnhSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAnhSP.setPreferredSize(new java.awt.Dimension(200, 100));
        anhSP.add(lblAnhSP, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pAnhLayout = new javax.swing.GroupLayout(pAnh);
        pAnh.setLayout(pAnhLayout);
        pAnhLayout.setHorizontalGroup(
            pAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAnhLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(anhSP, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pAnhLayout.setVerticalGroup(
            pAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAnhLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(anhSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );

        pCenter.add(pAnh, java.awt.BorderLayout.WEST);

        tableSP.setLayout(new java.awt.BorderLayout());

        spTableSP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setFocusable(false);
        table.setRowHeight(40);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowHorizontalLines(true);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        spTableSP.setViewportView(table);

        tableSP.add(spTableSP, java.awt.BorderLayout.CENTER);

        pTongHD.setBackground(new java.awt.Color(255, 255, 255));
        pTongHD.setPreferredSize(new java.awt.Dimension(800, 60));
        pTongHD.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        pTongHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pTongHoaDon.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        lblTongHD.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblTongHD.setForeground(new java.awt.Color(255, 51, 0));
        lblTongHD.setText("Tổng hóa đơn:");
        lblTongHD.setPreferredSize(new java.awt.Dimension(120, 40));
        pTongHoaDon.add(lblTongHD);

        txtTong.setEditable(false);
        txtTong.setFont(new java.awt.Font("Roboto Mono Medium", 0, 14)); // NOI18N
        txtTong.setForeground(new java.awt.Color(255, 51, 0));
        txtTong.setText("1000000");
        txtTong.setFocusable(false);
        txtTong.setPreferredSize(new java.awt.Dimension(200, 40));
        pTongHoaDon.add(txtTong);

        pTongHD.add(pTongHoaDon);

        tableSP.add(pTongHD, java.awt.BorderLayout.PAGE_END);

        pTitleCenter.setBackground(new java.awt.Color(204, 255, 204));
        pTitleCenter.setMinimumSize(new java.awt.Dimension(100, 60));
        pTitleCenter.setPreferredSize(new java.awt.Dimension(500, 30));
        pTitleCenter.setLayout(new java.awt.BorderLayout());

        lblThuoc.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblThuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThuoc.setText("Thông tin sản phẩm");
        pTitleCenter.add(lblThuoc, java.awt.BorderLayout.CENTER);

        tableSP.add(pTitleCenter, java.awt.BorderLayout.NORTH);

        pCenter.add(tableSP, java.awt.BorderLayout.CENTER);

        getContentPane().add(pCenter, java.awt.BorderLayout.CENTER);

        pSouth.setBackground(new java.awt.Color(255, 255, 255));
        pSouth.setPreferredSize(new java.awt.Dimension(1200, 50));
        pSouth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 5));

        btnHuy.setBackground(new java.awt.Color(255, 102, 102));
        btnHuy.setFont(new java.awt.Font("Roboto Mono Medium", 0, 16)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("HỦY BỎ");
        btnHuy.setBorderPainted(false);
        btnHuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHuy.setFocusPainted(false);
        btnHuy.setFocusable(false);
        btnHuy.setPreferredSize(new java.awt.Dimension(200, 40));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        pSouth.add(btnHuy);

        btnPrint.setBackground(new java.awt.Color(15, 204, 102));
        btnPrint.setFont(new java.awt.Font("Roboto Mono Medium", 0, 16)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("In hóa đơn");
        btnPrint.setBorderPainted(false);
        btnPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrint.setFocusPainted(false);
        btnPrint.setFocusable(false);
        btnPrint.setPreferredSize(new java.awt.Dimension(200, 40));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        pSouth.add(btnPrint);

        getContentPane().add(pSouth, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

    }//GEN-LAST:event_tableMouseClicked

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed

    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formThongTinPX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formThongTinPX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formThongTinPX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formThongTinPX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                formThongTinPX dialog = new formThongTinPX(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel anhSP;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jMaHD;
    private javax.swing.JLabel jTenKH;
    private javax.swing.JLabel lblAnhSP;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblThuoc;
    private javax.swing.JLabel lblTongHD;
    private javax.swing.JPanel pAnh;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pMaHD;
    private javax.swing.JPanel pNorth;
    private javax.swing.JPanel pSouth;
    private javax.swing.JPanel pTenKH;
    private javax.swing.JPanel pTenNV;
    private javax.swing.JPanel pThongTinHD;
    private javax.swing.JPanel pTilte;
    private javax.swing.JPanel pTitleCenter;
    private javax.swing.JPanel pTongHD;
    private javax.swing.JPanel pTongHoaDon;
    private javax.swing.JScrollPane spTableSP;
    private javax.swing.JTable table;
    private javax.swing.JPanel tableSP;
    private javax.swing.JLabel titleNorth;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTong;
    // End of variables declaration//GEN-END:variables
}
