/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.frame.ThongKe;

import DAO.ThongKe.ThongKeDAO;
import Entity.ThongKe.ThongKeTheoNam;
import Entity.ThongKe.ThongKeTheoThang;
import GUI.barchart.ModelChart;
import Utils.Formatter;
import Utils.MessageDialog;
import Utils.TableSorter;
import Utils.Validation;
import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roxan
 */
public class frmThongKeTheoNam extends javax.swing.JPanel {

    /**
     * Creates new form frmThongKeTheoNam
     */
    private List<ThongKeTheoThang> listTK;
    private DefaultTableModel modal;
    private ThongKeDAO thongKeDAO;

    public frmThongKeTheoNam() {
        initComponents();
        thongKeDAO = new ThongKeDAO(); // Khởi tạo ThongKeDAO để truy vấn trực tiếp
        chartLayout();
        tableLayout();
        loadDataset();
        tinhTong();
    }

    // Tính tổng doanh thu, vốn và lợi nhuận
    private void tinhTong() {
        long tongDoanhThu = 0;
        long tongVon = 0;

        for (ThongKeTheoThang e : listTK) {
            tongDoanhThu += e.getDoanhThu();
            tongVon += e.getVon();
        }

        long loiNhuan = tongDoanhThu - tongVon;
        java.text.NumberFormat nf = java.text.NumberFormat.getInstance(new java.util.Locale("vi", "VN"));
        lblTongDoanhThu.setText(nf.format(tongDoanhThu) + "đ");
        lblTongVon.setText(nf.format(tongVon) + "đ");
        txtTongLoiNhuan.setText(nf.format(loiNhuan) + "đ");
    }

    // chartLayout
    private void chartLayout() {
        pThongKe.addLegend("Doanh thu", new Color(135, 189, 245));
        pThongKe.addLegend("Vốn", new Color(245, 189, 135)); // đổi tên
        pThongKe.addLegend("Lợi nhuận", new Color(139, 225, 196));
        pThongKe.start();
    }

    // loadChart
    private void loadChart() {
        for (ThongKeTheoThang e : listTK) {
            double loiNhuan = e.getDoanhThu() - e.getVon();
            pThongKe.addData(new ModelChart("Tháng " + e.getThang(),
                    new double[] { e.getDoanhThu(), e.getVon(), loiNhuan }));
        }
    }

    // tableLayout
    private void tableLayout() {
        String[] header = new String[] { "Tháng", "Doanh thu", "Vốn", "Lợi nhuận" }; // đổi Chi phí thành Vốn
        modal = new DefaultTableModel();
        modal.setColumnIdentifiers(header);
        table.setModel(modal);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        sortTable();
    }

    // Sắp xếp bảng
    private void sortTable() {
        table.setAutoCreateRowSorter(true);
        TableSorter.configureTableColumnSorter(table, 0, TableSorter.STRING_COMPARATOR);
    }

    // loadTable
    private void loadTable() {
        modal.setRowCount(0);
        for (ThongKeTheoThang e : listTK) {
            long loiNhuan = (long) (e.getDoanhThu() - e.getVon());
            modal.addRow(new Object[] {
                    "Tháng " + e.getThang(),
                    Formatter.FormatVND(e.getDoanhThu()),
                    Formatter.FormatVND(e.getVon()),
                    Formatter.FormatVND(loiNhuan)
            });
        }
    }

    // Tải dữ liệu thống kê (biểu đồ và bảng) theo 1 năm duy nhất
    private void loadDataset() {
        pThongKe.clear();

        int nam = txtNam.getValue(); // Lấy năm từ JSpinField
        listTK = thongKeDAO.getThongKeTheoNam(nam); // Trả về List<ThongKeTheoThang>

        loadChart();
        loadTable();
        tinhTong(); // Tính tổng doanh thu, vốn và lợi nhuận
        pThongKe.start();
    }

    private boolean isValidFilterFields() {
        if (txtNam.getValue() < 1900 || txtNam.getValue() > LocalDate.now().getYear()) {
            MessageDialog.warring(this, "Năm phải từ 1900 đến " + LocalDate.now().getYear());
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pNorth = new javax.swing.JPanel();
        lblNam = new javax.swing.JLabel();
        txtNam = new com.toedter.components.JSpinField();
        btnThongKe = new javax.swing.JButton();
        pSouth = new javax.swing.JPanel();
        pSouth_all = new javax.swing.JPanel();
        jspTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        pTong = new javax.swing.JPanel();
        plblTong = new javax.swing.JPanel();
        lblTong = new javax.swing.JLabel();
        pDoanhThu = new javax.swing.JPanel();
        lblDoanhThu = new javax.swing.JLabel();
        lblTongDoanhThu = new javax.swing.JLabel();
        pVon = new javax.swing.JPanel();
        lblVon = new javax.swing.JLabel();
        lblTongVon = new javax.swing.JLabel();
        pLoiNhuan = new javax.swing.JPanel();
        txtLoiNhuan = new javax.swing.JLabel();
        txtTongLoiNhuan = new javax.swing.JLabel();
        jspThongKe = new javax.swing.JScrollPane();
        pThongKe = new GUI.barchart.chart();

        setMinimumSize(new java.awt.Dimension(1130, 800));
        setLayout(new java.awt.BorderLayout());

        pNorth.setBackground(new java.awt.Color(247, 247, 247));
        pNorth.setPreferredSize(new java.awt.Dimension(1200, 80));
        pNorth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 30));

        lblNam.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblNam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNam.setText("Năm:");
        lblNam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNam.setPreferredSize(new java.awt.Dimension(40, 30));
        pNorth.add(lblNam);

        txtNam.setPreferredSize(new java.awt.Dimension(80, 26));
        txtNam.setValue(2025);
        pNorth.add(txtNam);

        btnThongKe.setBackground(new java.awt.Color(51, 153, 255));
        btnThongKe.setForeground(new java.awt.Color(204, 255, 255));
        btnThongKe.setText("Thống kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        pNorth.add(btnThongKe);

        add(pNorth, java.awt.BorderLayout.NORTH);

        pSouth.setMinimumSize(new java.awt.Dimension(1200, 250));
        pSouth.setPreferredSize(new java.awt.Dimension(1200, 300));
        pSouth.setLayout(new java.awt.BorderLayout());

        pSouth_all.setPreferredSize(new java.awt.Dimension(1200, 300));
        pSouth_all.setLayout(new java.awt.BorderLayout());

        jspTable.setMinimumSize(new java.awt.Dimension(1200, 250));
        jspTable.setPreferredSize(new java.awt.Dimension(1200, 300));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tháng", "Doanh thu", "Vốn", "Lợi nhuận"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setFocusable(false);
        table.setRowHeight(40);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowHorizontalLines(true);
        jspTable.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(3).setResizable(false);
        }

        pSouth_all.add(jspTable, java.awt.BorderLayout.CENTER);

        plblTong.setMaximumSize(new java.awt.Dimension(230, 30));
        plblTong.setMinimumSize(new java.awt.Dimension(230, 30));
        plblTong.setPreferredSize(new java.awt.Dimension(230, 30));

        lblTong.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTong.setForeground(new java.awt.Color(255, 0, 51));
        lblTong.setText("TỔNG:");
        lblTong.setMaximumSize(new java.awt.Dimension(60, 25));
        lblTong.setMinimumSize(new java.awt.Dimension(60, 25));
        lblTong.setPreferredSize(new java.awt.Dimension(60, 25));
        lblTong.setRequestFocusEnabled(false);
        plblTong.add(lblTong);

        pTong.add(plblTong);

        pDoanhThu.setPreferredSize(new java.awt.Dimension(250, 30));
        pDoanhThu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDoanhThu.setText("Doanh thu:");
        pDoanhThu.add(lblDoanhThu);

        lblTongDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongDoanhThu.setForeground(new java.awt.Color(102, 102, 102));
        lblTongDoanhThu.setPreferredSize(new java.awt.Dimension(150, 30));
        pDoanhThu.add(lblTongDoanhThu);

        pTong.add(pDoanhThu);

        pVon.setMinimumSize(new java.awt.Dimension(250, 30));
        pVon.setPreferredSize(new java.awt.Dimension(250, 30));
        pVon.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblVon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVon.setText("Vốn:");
        pVon.add(lblVon);

        lblTongVon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongVon.setForeground(new java.awt.Color(102, 102, 102));
        lblTongVon.setMaximumSize(new java.awt.Dimension(150, 30));
        lblTongVon.setMinimumSize(new java.awt.Dimension(150, 30));
        lblTongVon.setPreferredSize(new java.awt.Dimension(150, 30));
        pVon.add(lblTongVon);

        pTong.add(pVon);

        pLoiNhuan.setMinimumSize(new java.awt.Dimension(250, 30));
        pLoiNhuan.setPreferredSize(new java.awt.Dimension(250, 30));

        txtLoiNhuan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtLoiNhuan.setText("Lợi nhuận:");
        pLoiNhuan.add(txtLoiNhuan);

        txtTongLoiNhuan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTongLoiNhuan.setForeground(new java.awt.Color(102, 102, 102));
        txtTongLoiNhuan.setMaximumSize(new java.awt.Dimension(150, 30));
        txtTongLoiNhuan.setMinimumSize(new java.awt.Dimension(150, 30));
        txtTongLoiNhuan.setPreferredSize(new java.awt.Dimension(150, 30));
        pLoiNhuan.add(txtTongLoiNhuan);

        pTong.add(pLoiNhuan);

        pSouth_all.add(pTong, java.awt.BorderLayout.SOUTH);

        pSouth.add(pSouth_all, java.awt.BorderLayout.SOUTH);

        add(pSouth, java.awt.BorderLayout.SOUTH);

        jspThongKe.setPreferredSize(new java.awt.Dimension(1200, 110));

        pThongKe.setMinimumSize(new java.awt.Dimension(2000, 100));
        pThongKe.setPreferredSize(new java.awt.Dimension(1200, 350));
        jspThongKe.setViewportView(pThongKe);

        add(jspThongKe, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThongKeActionPerformed
        if (isValidFilterFields()) {
            loadDataset();
        }
    }// GEN-LAST:event_btnThongKeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThongKe;
    private javax.swing.JScrollPane jspTable;
    private javax.swing.JScrollPane jspThongKe;
    private javax.swing.JLabel lblDoanhThu;
    private javax.swing.JLabel lblNam;
    private javax.swing.JLabel lblTong;
    private javax.swing.JLabel lblTongDoanhThu;
    private javax.swing.JLabel lblTongVon;
    private javax.swing.JLabel lblVon;
    private javax.swing.JPanel pDoanhThu;
    private javax.swing.JPanel pLoiNhuan;
    private javax.swing.JPanel pNorth;
    private javax.swing.JPanel pSouth;
    private javax.swing.JPanel pSouth_all;
    private GUI.barchart.chart pThongKe;
    private javax.swing.JPanel pTong;
    private javax.swing.JPanel pVon;
    private javax.swing.JPanel plblTong;
    private javax.swing.JTable table;
    private javax.swing.JLabel txtLoiNhuan;
    private com.toedter.components.JSpinField txtNam;
    private javax.swing.JLabel txtTongLoiNhuan;
    // End of variables declaration//GEN-END:variables
}
