/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.form.KhachHang;

import Entity.KhachHang.KhachHang;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author ADMIN
 */
public class formThongTinKH extends javax.swing.JDialog {
    private ButtonGroup grpGioiTinh;

    /**
     * Creates new form formThongTinKH
     * @param parent
     * @param modal
     * @param kh
     */
    public formThongTinKH(java.awt.Frame parent, boolean modal, KhachHang kh) {
        super(parent, modal);
        initComponents();
        groupGenderButtons();
        configureTable();
        disableTextFieldFocus();
        setThongTinKH(kh);
    }

    private void groupGenderButtons() {
        grpGioiTinh = new ButtonGroup();
        grpGioiTinh.add(rbtnNam);
        grpGioiTinh.add(rbtnNu);
    }

    private void configureTable() {
        // Căn giữa cho tất cả các cell trong bảng
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        // Căn giữa cho từng cột
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Ngăn không cho phép chọn nhiều dòng
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setRowSelectionAllowed(true);
        table.setColumnSelectionAllowed(false);
    }

    private void setThongTinKH(Entity.KhachHang.KhachHang kh) {
        if (kh == null)
            return;
        txtMaKH.setText(kh.getMaKH());
        txtHoTen.setText(kh.getTenKH());
        txtSDT.setText(kh.getSdt());
        // Bổ sung giới tính
        String gioiTinh = kh.getGioiTinh(); // giả sử "Nam" hoặc "Nữ"
        if ("Nam".equalsIgnoreCase(gioiTinh)) {
            rbtnNam.setSelected(true);
        } else if ("Nữ".equalsIgnoreCase(gioiTinh)) {
            rbtnNu.setSelected(true);
        } else {
            grpGioiTinh.clearSelection(); // Nếu không xác định
        }

        loadHoaDonTheoKH(kh.getMaKH());
    }

    private void disableTextFieldFocus() {
        txtMaKH.setEditable(false);
        txtMaKH.setFocusable(false);

        txtHoTen.setEditable(false);
        txtHoTen.setFocusable(false);

        txtSDT.setEditable(false);
        txtSDT.setFocusable(false);

    }

    private void loadHoaDonTheoKH(String maKH) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) table.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ trong bảng

        DAO.HoaDon.HoaDonDAO dao = new DAO.HoaDon.HoaDonDAO();
        java.util.List<Object[]> list = dao.findByMaKH(maKH);

        int stt = 1;
        java.text.DecimalFormat df = new java.text.DecimalFormat("#,##0 VNĐ");
        java.time.format.DateTimeFormatter dtf = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

        for (Object[] row : list) {
            String maHD = (String) row[0];
            String tenNV = (String) row[1];
            java.time.LocalDateTime thoiGian = (java.time.LocalDateTime) row[2];
            double tongTien = (double) row[3];
            String kieuThanhToan = row.length > 4 ? (String) row[4] : "";

            model.addRow(new Object[] {
                    stt++,
                    maHD,
                    tenNV,
                    thoiGian != null ? dtf.format(thoiGian) : "",
                    df.format(tongTien),
                    kieuThanhToan
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        roundPanel = new Swing.RoundPanel();
        pNorth = new javax.swing.JPanel();
        lblThemKH = new javax.swing.JLabel();
        pCenter = new javax.swing.JPanel();
        pThongTin = new javax.swing.JPanel();
        lblMaKH = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        lblTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblGioiTinh = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbtnNam = new javax.swing.JRadioButton();
        rbtnNu = new javax.swing.JRadioButton();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        pTilteTable = new javax.swing.JPanel();
        tilteTable = new javax.swing.JLabel();
        scrollTableCenter = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        pSouth = new javax.swing.JPanel();
        btnHuy = new javax.swing.JButton();
        btnChiTiet = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));

        roundPanel.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel.setMaximumSize(new java.awt.Dimension(600, 600));
        roundPanel.setMinimumSize(new java.awt.Dimension(600, 600));
        roundPanel.setName(""); // NOI18N
        roundPanel.setPreferredSize(new java.awt.Dimension(600, 600));
        roundPanel.setLayout(new java.awt.BorderLayout());

        pNorth.setBackground(new java.awt.Color(204, 255, 204));
        pNorth.setMaximumSize(new java.awt.Dimension(600, 50));
        pNorth.setLayout(new java.awt.BorderLayout());

        lblThemKH.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblThemKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThemKH.setText(" Thông tin khách hàng");
        lblThemKH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblThemKH.setMaximumSize(new java.awt.Dimension(600, 50));
        lblThemKH.setMinimumSize(new java.awt.Dimension(600, 50));
        lblThemKH.setPreferredSize(new java.awt.Dimension(600, 50));
        pNorth.add(lblThemKH, java.awt.BorderLayout.CENTER);

        roundPanel.add(pNorth, java.awt.BorderLayout.PAGE_START);

        pCenter.setBackground(new java.awt.Color(255, 255, 255));
        pCenter.setMaximumSize(new java.awt.Dimension(600, 300));
        pCenter.setMinimumSize(new java.awt.Dimension(600, 300));
        pCenter.setPreferredSize(new java.awt.Dimension(600, 300));

        pThongTin.setBackground(new java.awt.Color(255, 255, 255));
        pThongTin.setMaximumSize(new java.awt.Dimension(550, 150));
        pThongTin.setMinimumSize(new java.awt.Dimension(550, 150));
        pThongTin.setPreferredSize(new java.awt.Dimension(550, 150));
        pThongTin.setLayout(new java.awt.GridLayout(5, 2, 5, 0));

        lblMaKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaKH.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaKH.setText("Mã khách hàng:");
        lblMaKH.setAlignmentX(20.0F);
        lblMaKH.setAlignmentY(20.0F);
        pThongTin.add(lblMaKH);

        txtMaKH.setEditable(false);
        txtMaKH.setPreferredSize(new java.awt.Dimension(350, 22));
        txtMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaKHActionPerformed(evt);
            }
        });
        pThongTin.add(txtMaKH);

        lblTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTen.setText("Họ tên:");
        lblTen.setAlignmentX(20.0F);
        lblTen.setAlignmentY(20.0F);
        pThongTin.add(lblTen);

        txtHoTen.setEditable(false);
        txtHoTen.setPreferredSize(new java.awt.Dimension(350, 22));
        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });
        pThongTin.add(txtHoTen);

        lblGioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGioiTinh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGioiTinh.setText("Giới tính:");
        pThongTin.add(lblGioiTinh);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        rbtnNam.setText("Nam");
        rbtnNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNamActionPerformed(evt);
            }
        });
        jPanel2.add(rbtnNam);

        rbtnNu.setText("Nữ");
        jPanel2.add(rbtnNu);

        pThongTin.add(jPanel2);

        lblSDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSDT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSDT.setText("SĐT:");
        pThongTin.add(lblSDT);

        txtSDT.setEditable(false);
        txtSDT.setPreferredSize(new java.awt.Dimension(350, 22));
        pThongTin.add(txtSDT);

        pCenter.add(pThongTin);

        pTilteTable.setMinimumSize(new java.awt.Dimension(550, 40));
        pTilteTable.setPreferredSize(new java.awt.Dimension(550, 40));

        tilteTable.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tilteTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tilteTable.setText("Lịch sử giao dịch");
        tilteTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tilteTable.setMaximumSize(new java.awt.Dimension(600, 40));
        tilteTable.setMinimumSize(new java.awt.Dimension(600, 40));
        tilteTable.setPreferredSize(new java.awt.Dimension(600, 40));
        pTilteTable.add(tilteTable);

        pCenter.add(pTilteTable);

        scrollTableCenter.setMinimumSize(new java.awt.Dimension(550, 280));
        scrollTableCenter.setPreferredSize(new java.awt.Dimension(550, 280));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã hóa đơn", "Tên nhân viên", "Ngày mua", "Tổng hóa đơn", "Kiểu thanh toán"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setMaximumSize(null);
        table.setName(""); // NOI18N
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowHorizontalLines(true);
        scrollTableCenter.setViewportView(table);

        pCenter.add(scrollTableCenter);

        roundPanel.add(pCenter, java.awt.BorderLayout.CENTER);

        pSouth.setBackground(new java.awt.Color(255, 255, 255));
        pSouth.setMaximumSize(new java.awt.Dimension(600, 50));
        pSouth.setMinimumSize(new java.awt.Dimension(600, 50));
        pSouth.setPreferredSize(new java.awt.Dimension(600, 50));

        btnHuy.setBackground(new java.awt.Color(255, 103, 102));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Huỷ");
        btnHuy.setPreferredSize(new java.awt.Dimension(90, 35));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        pSouth.add(btnHuy);

        btnChiTiet.setBackground(new java.awt.Color(15, 204, 102));
        btnChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTiet.setText("Chi tiết");
        btnChiTiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChiTiet.setMaximumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setMinimumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setPreferredSize(new java.awt.Dimension(90, 35));
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });
        pSouth.add(btnChiTiet);

        roundPanel.add(pSouth, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(roundPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        dispose();
    }// GEN-LAST:event_btnHuyActionPerformed

    private void txtMaKHActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtMaKHActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtMaKHActionPerformed

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtHoTenActionPerformed

    private void rbtnNamActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rbtnNamActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_rbtnNamActionPerformed

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnChiTietActionPerformed
        // TODO add your handling code here:
                int row = table.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn một hóa đơn để xem chi tiết!",
                    "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Giả định cột 0 là STT, cột 1 là Mã hóa đơn
        String maHD = table.getValueAt(row, 1).toString().trim();
        if (maHD.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Không thể xác định mã hóa đơn!",
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Kiểm tra hóa đơn có tồn tại không
        DAO.HoaDon.HoaDonDAO hdDao = new DAO.HoaDon.HoaDonDAO();
        Entity.HoaDon.HoaDon hd = hdDao.findById(maHD).orElse(null);
        if (hd == null) {
            JOptionPane.showMessageDialog(this,
                    "Không tìm thấy hóa đơn có mã: " + maHD,
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Mở form chi tiết hóa đơn
        javax.swing.JFrame parentFrame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        GUI.form.HoaDon.formThongTinHD frm = new GUI.form.HoaDon.formThongTinHD(parentFrame, false, hd);
        frm.setLocationRelativeTo(this);
        frm.setVisible(true);
    }// GEN-LAST:event_btnChiTietActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
//        // (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
//         * look and feel.
//         * For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(formThongTinKH.class.getName()).log(java.util.logging.Level.SEVERE, null,
//                    ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(formThongTinKH.class.getName()).log(java.util.logging.Level.SEVERE, null,
//                    ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(formThongTinKH.class.getName()).log(java.util.logging.Level.SEVERE, null,
//                    ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(formThongTinKH.class.getName()).log(java.util.logging.Level.SEVERE, null,
//                    ex);
//        }
//        // </editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                formThongTinKH dialog = new formThongTinKH(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnHuy;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblThemKH;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pNorth;
    private javax.swing.JPanel pSouth;
    private javax.swing.JPanel pThongTin;
    private javax.swing.JPanel pTilteTable;
    private javax.swing.JRadioButton rbtnNam;
    private javax.swing.JRadioButton rbtnNu;
    private Swing.RoundPanel roundPanel;
    private javax.swing.JScrollPane scrollTableCenter;
    private javax.swing.JTable table;
    private javax.swing.JLabel tilteTable;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
