/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.frame.NhanVien;

import DAO.NhanVien.NhanVienDAO;
import GUI.form.NhanVien.formThemNV;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class frmNhanVien extends javax.swing.JPanel {
    /**
     * Creates new form frmNhanVien
     */
    public frmNhanVien() {
        initComponents();
        configureTable();
        loadDataTable();
    }
    private void configureTable() {
        // Ngăn không cho phép người dùng chỉnh sửa bảng
        table.setDefaultEditor(Object.class, null);                                                   

        // Căn giữa cho tất cả các cell trong bảng
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        // Căn giữa cho từng cột
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Ngăn không cho phép chọn nhiều dòng
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }
    private void loadDataTable() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);

        NhanVienDAO dao = new NhanVienDAO();
        List<Object[]> list = dao.findAllWithDetails(); // [maNV, tenNV, chucVu, SDT, "Nam/Nữ", "Đang làm/Nghỉ việc"]

        int stt = 1;
        for (Object[] r : list) {
            model.addRow(new Object[]{
                stt++,    // STT
                r[0],     // Mã nhân viên
                r[1],     // Tên nhân viên
                r[2],     // Chức vụ
                r[3],     // SĐT
                r[4],     // Giới tính (đã là "Nam"/"Nữ")
                r[5]      // Trạng thái (đã là "Đang làm"/"Nghỉ việc")
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        pNorth = new javax.swing.JPanel();
        titleName = new javax.swing.JLabel();
        pCongCu = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        pCenter = new javax.swing.JPanel();
        scrollTableCenter = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        pSouth = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnChiTiet = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        Panel.setMinimumSize(new java.awt.Dimension(1200, 600));
        Panel.setName(""); // NOI18N
        Panel.setLayout(new java.awt.BorderLayout());

        pNorth.setBackground(new java.awt.Color(204, 255, 204));
        pNorth.setMinimumSize(new java.awt.Dimension(1200, 50));
        pNorth.setName(""); // NOI18N
        pNorth.setPreferredSize(new java.awt.Dimension(1200, 100));
        pNorth.setLayout(new java.awt.BorderLayout());

        titleName.setBackground(new java.awt.Color(0, 0, 0));
        titleName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleName.setText("Danh sách nhân viên");
        titleName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titleName.setMinimumSize(new java.awt.Dimension(1200, 32));
        titleName.setPreferredSize(new java.awt.Dimension(1200, 32));
        pNorth.add(titleName, java.awt.BorderLayout.CENTER);

        pCongCu.setBackground(new java.awt.Color(222, 222, 222));
        pCongCu.setMinimumSize(new java.awt.Dimension(1200, 40));
        pCongCu.setPreferredSize(new java.awt.Dimension(1200, 35));
        pCongCu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 3));

        txtTimKiem.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtTimKiem.setMinimumSize(new java.awt.Dimension(150, 30));
        txtTimKiem.setName(""); // NOI18N
        txtTimKiem.setPreferredSize(new java.awt.Dimension(200, 25));
        pCongCu.add(txtTimKiem);

        btnTimKiem.setBackground(new java.awt.Color(0, 204, 51));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        btnTimKiem.setMaximumSize(new java.awt.Dimension(80, 30));
        btnTimKiem.setMinimumSize(new java.awt.Dimension(80, 30));
        btnTimKiem.setPreferredSize(new java.awt.Dimension(80, 30));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        pCongCu.add(btnTimKiem);

        pNorth.add(pCongCu, java.awt.BorderLayout.PAGE_END);

        Panel.add(pNorth, java.awt.BorderLayout.PAGE_START);

        pCenter.setMinimumSize(new java.awt.Dimension(0, 0));
        pCenter.setLayout(new java.awt.BorderLayout());

        scrollTableCenter.setMinimumSize(new java.awt.Dimension(1200, 500));
        scrollTableCenter.setPreferredSize(new java.awt.Dimension(1200, 500));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã nhân viên", "Tên nhân viên", "Chức vụ", "SĐT", "Giới tính", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setMinimumSize(null);
        table.setName(""); // NOI18N
        table.setPreferredSize(null);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowHorizontalLines(true);
        scrollTableCenter.setViewportView(table);

        pCenter.add(scrollTableCenter, java.awt.BorderLayout.CENTER);

        Panel.add(pCenter, java.awt.BorderLayout.CENTER);

        pSouth.setBackground(new java.awt.Color(222, 222, 222));
        pSouth.setMinimumSize(new java.awt.Dimension(1200, 50));
        pSouth.setPreferredSize(new java.awt.Dimension(1200, 50));

        btnThem.setBackground(new java.awt.Color(15, 204, 102));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThem.setMaximumSize(new java.awt.Dimension(85, 35));
        btnThem.setMinimumSize(new java.awt.Dimension(85, 35));
        btnThem.setPreferredSize(new java.awt.Dimension(105, 35));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pSouth.add(btnThem);

        btnXoa.setBackground(new java.awt.Color(255, 102, 102));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoa.setMaximumSize(new java.awt.Dimension(85, 35));
        btnXoa.setMinimumSize(new java.awt.Dimension(85, 35));
        btnXoa.setPreferredSize(new java.awt.Dimension(105, 35));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pSouth.add(btnXoa);

        btnSua.setBackground(new java.awt.Color(204, 204, 204));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSua.setMaximumSize(new java.awt.Dimension(85, 35));
        btnSua.setMinimumSize(new java.awt.Dimension(85, 35));
        btnSua.setPreferredSize(new java.awt.Dimension(105, 35));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        pSouth.add(btnSua);

        btnChiTiet.setBackground(new java.awt.Color(153, 153, 153));
        btnChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTiet.setText("Chi tiết");
        btnChiTiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChiTiet.setMaximumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setMinimumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setPreferredSize(new java.awt.Dimension(105, 35));
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });
        pSouth.add(btnChiTiet);

        Panel.add(pSouth, java.awt.BorderLayout.PAGE_END);

        add(Panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        formThemNV dialog = new formThemNV(parentFrame, true); // Mở formThemNV
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        // Sau khi đóng formThemNV, gọi lại phương thức để làm mới bảng
        loadDataTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedRow = table.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản để xoá!");
            return;
        }

        String maNV = table.getValueAt(selectedRow, 1).toString();

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc muốn xoá tài khoản: " + maNV + " ?",
                "Xác nhận xoá",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirm != JOptionPane.YES_OPTION)
            return;

        try {
            NhanVienDAO nvDAO = new NhanVienDAO();
            boolean success = nvDAO.delete(maNV);

            if (success) {
                JOptionPane.showMessageDialog(this, "Đã xoá nhân viên thành công!");
                loadDataTable();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Không thể xoá! Nhân viên không tồn tại hoặc đang được tham chiếu.");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Có lỗi khi xoá: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if (row < 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn một nhân viên để sửa!",
                    "Thông báo", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String maNV = table.getValueAt(row, 1).toString();

        DAO.NhanVien.NhanVienDAO dao = new DAO.NhanVien.NhanVienDAO();
        Entity.NhanVien.NhanVien nv = dao.findById(maNV).orElse(null);

        if (nv == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Không tìm thấy thông tin nhân viên!",
                    "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Mở form chi tiết
        javax.swing.JFrame parent = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        GUI.form.NhanVien.formSuaNV dialog = new GUI.form.NhanVien.formSuaNV(parent, true, nv);

        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        loadDataTable();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String keyword = txtTimKiem.getText().trim().toLowerCase();

        // Lấy model của bảng
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ

        NhanVienDAO dao = new NhanVienDAO();
        List<Object[]> list = dao.findAllWithDetails(); // Lấy danh sách nhân viên (Object[])

        // Lọc danh sách theo từ khóa
        if (!keyword.isEmpty()) {
            list = list.stream()
                    .filter(r ->
                            (r[0] != null && r[0].toString().toLowerCase().contains(keyword)) || // maNV
                            (r[1] != null && r[1].toString().toLowerCase().contains(keyword))    // tenNV
                    )
                    .toList();
        }

        // Đổ dữ liệu vào table
        int stt = 1;
        for (Object[] r : list) {
            model.addRow(new Object[]{
                    stt++,      // STT
                    r[0],       // Mã nhân viên
                    r[1],       // Tên nhân viên
                    r[2],       // Chức vụ
                    r[3],       // SĐT
                    r[4],       // Giới tính
                    r[5]        // Trạng thái
            });
        }

        // Thông báo nếu không tìm thấy
        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Không tìm thấy nhân viên phù hợp với: " + keyword);
        }

    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if (row < 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn một nhân viên để xem chi tiết!",
                    "Thông báo", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lấy mã nhà cung cấp từ bảng
        String maNV = table.getValueAt(row, 1).toString();

        // Lấy dữ liệu từ DAO
        DAO.NhanVien.NhanVienDAO dao = new DAO.NhanVien.NhanVienDAO();
        Entity.NhanVien.NhanVien nv = dao.findById(maNV).orElse(null);

        if (nv == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Không tìm thấy thông tin nhân viên!",
                    "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Mở form chi tiết
        javax.swing.JFrame parent = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        GUI.form.NhanVien.formThongTinNV dialog = new GUI.form.NhanVien.formThongTinNV(parent, true, nv);

        // Gán dữ liệu vào form
        dialog.setTitle("Thông tin tài khoản - " + nv.getTenNV());
        dialog.setLocationRelativeTo(this);

        dialog.setVisible(true);
        loadDataTable();
    }//GEN-LAST:event_btnChiTietActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pCongCu;
    private javax.swing.JPanel pNorth;
    private javax.swing.JPanel pSouth;
    private javax.swing.JScrollPane scrollTableCenter;
    private javax.swing.JTable table;
    private javax.swing.JLabel titleName;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
