/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.frame.NhanVien;

import DAO.NhanVien.NhanVienDAO;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class frmSearchNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form frmSearchNhanVien
     */
    public frmSearchNhanVien() {
        initComponents();
        configureTable();
        loadDataTable();
        loadComboChucVu();
    }
    private void configureTable() {
        // Ngăn không cho phép người dùng chỉnh sửa bảng
        table.setDefaultEditor(Object.class, null);                                                   

        // Căn giữa cho tất cả các cell trong bảng
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        // Căn giữa cho từng cột
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Ngăn không cho phép chọn nhiều dòng
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }
    private void loadComboChucVu() {
        cboChucVu.removeAllItems(); 

        cboChucVu.addItem("Tất cả");     // index 0
        cboChucVu.addItem("Quản lý");    // index 1
        cboChucVu.addItem("Nhân viên");  // index 2

        cboChucVu.setSelectedIndex(0);  // mặc định chọn "Tất cả"
    }

    private void loadDataTable() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);

        NhanVienDAO dao = new NhanVienDAO();
        List<Object[]> list = dao.findAllWithDetails(); // [maNV, tenNV, chucVu, SDT, "Nam/Nữ", "Đang làm/Nghỉ việc"]

        int stt = 1;
        for (Object[] r : list) {
            model.addRow(new Object[]{
                stt++,    // STT
                r[0],     // Mã nhân viên
                r[1],     // Tên nhân viên
                r[2],     // Chức vụ
                r[3],     // SĐT
                r[4],     // Giới tính (đã là "Nam"/"Nữ")
                r[5]      // Trạng thái (đã là "Đang làm"/"Nghỉ việc")
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        pNorth = new javax.swing.JPanel();
        northTilte = new javax.swing.JPanel();
        titleName = new javax.swing.JLabel();
        pTimKiem = new javax.swing.JPanel();
        pTimKiem_Row1 = new javax.swing.JPanel();
        pTimKiem_Row1_Col1 = new javax.swing.JPanel();
        lblMaNV = new javax.swing.JLabel();
        pTimKiem_Row1_Col2 = new javax.swing.JPanel();
        txtMaNV = new java.awt.TextField();
        pTimKiem_Row2 = new javax.swing.JPanel();
        pTimKiem_Row2_Col1 = new javax.swing.JPanel();
        lblTenNV = new javax.swing.JLabel();
        pTimKiem_Row2_Col2 = new javax.swing.JPanel();
        txtTenNV = new java.awt.TextField();
        pTimKiem_Row3 = new javax.swing.JPanel();
        pTimKiem_Row3_Col1 = new javax.swing.JPanel();
        lblSDT = new javax.swing.JLabel();
        pTimKiem_Row3_Col2 = new javax.swing.JPanel();
        txtSDT = new java.awt.TextField();
        pTimKiem_Row4 = new javax.swing.JPanel();
        pTimKiem_Row4_Col1 = new javax.swing.JPanel();
        lblChucVu = new javax.swing.JLabel();
        pTimKiem_Row4_Col2 = new javax.swing.JPanel();
        cboChucVu = new javax.swing.JComboBox<>();
        pTimKiem_Row5 = new javax.swing.JPanel();
        pTimKiem_Row5_Col1 = new javax.swing.JPanel();
        pTimKiem_Row5_Col2 = new javax.swing.JPanel();
        btnTim = new javax.swing.JButton();
        pCenter = new javax.swing.JPanel();
        scrollTableCenter = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        centerTilte = new javax.swing.JPanel();
        titleName1 = new javax.swing.JLabel();
        pSouth = new javax.swing.JPanel();
        btnChiTiet = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        Panel.setName(""); // NOI18N
        Panel.setLayout(new java.awt.BorderLayout());

        pNorth.setBackground(new java.awt.Color(204, 255, 204));
        pNorth.setMinimumSize(new java.awt.Dimension(1200, 250));
        pNorth.setName(""); // NOI18N
        pNorth.setPreferredSize(new java.awt.Dimension(1200, 250));
        pNorth.setLayout(new java.awt.BorderLayout());

        northTilte.setBackground(new java.awt.Color(204, 255, 204));
        northTilte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        northTilte.setMinimumSize(new java.awt.Dimension(1200, 50));
        northTilte.setPreferredSize(new java.awt.Dimension(1200, 50));
        northTilte.setLayout(new java.awt.BorderLayout());

        titleName.setBackground(new java.awt.Color(0, 0, 0));
        titleName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleName.setText("Tìm kiếm nhân viên");
        titleName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titleName.setMinimumSize(new java.awt.Dimension(1200, 32));
        titleName.setPreferredSize(new java.awt.Dimension(1200, 32));
        northTilte.add(titleName, java.awt.BorderLayout.CENTER);

        pNorth.add(northTilte, java.awt.BorderLayout.NORTH);

        pTimKiem.setMinimumSize(new java.awt.Dimension(829, 300));
        pTimKiem.setLayout(new javax.swing.BoxLayout(pTimKiem, javax.swing.BoxLayout.Y_AXIS));

        pTimKiem_Row1.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row1.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row1_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row1_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row1_Col1.setLayout(new java.awt.BorderLayout());

        lblMaNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaNV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaNV.setText("Mã nhân viên:");
        lblMaNV.setAlignmentX(20.0F);
        lblMaNV.setAlignmentY(20.0F);
        pTimKiem_Row1_Col1.add(lblMaNV, java.awt.BorderLayout.CENTER);

        pTimKiem_Row1.add(pTimKiem_Row1_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row1_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row1_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row1_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        txtMaNV.setMaximumSize(new java.awt.Dimension(350, 32));
        txtMaNV.setMinimumSize(new java.awt.Dimension(350, 32));
        txtMaNV.setPreferredSize(new java.awt.Dimension(350, 30));
        pTimKiem_Row1_Col2.add(txtMaNV);

        pTimKiem_Row1.add(pTimKiem_Row1_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem.add(pTimKiem_Row1);

        pTimKiem_Row2.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row2.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row2_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row2_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row2_Col1.setLayout(new java.awt.BorderLayout());

        lblTenNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenNV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTenNV.setText("Tên nhân viên:");
        lblTenNV.setAlignmentX(20.0F);
        lblTenNV.setAlignmentY(20.0F);
        pTimKiem_Row2_Col1.add(lblTenNV, java.awt.BorderLayout.CENTER);

        pTimKiem_Row2.add(pTimKiem_Row2_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row2_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row2_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row2_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        txtTenNV.setMaximumSize(new java.awt.Dimension(350, 32));
        txtTenNV.setMinimumSize(new java.awt.Dimension(350, 32));
        txtTenNV.setPreferredSize(new java.awt.Dimension(350, 30));
        pTimKiem_Row2_Col2.add(txtTenNV);

        pTimKiem_Row2.add(pTimKiem_Row2_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem.add(pTimKiem_Row2);

        pTimKiem_Row3.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row3.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row3_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row3_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row3_Col1.setLayout(new java.awt.BorderLayout());

        lblSDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSDT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSDT.setText("Số điện thoại:");
        lblSDT.setAlignmentX(20.0F);
        lblSDT.setAlignmentY(20.0F);
        pTimKiem_Row3_Col1.add(lblSDT, java.awt.BorderLayout.CENTER);

        pTimKiem_Row3.add(pTimKiem_Row3_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row3_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row3_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row3_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        txtSDT.setMaximumSize(new java.awt.Dimension(350, 32));
        txtSDT.setMinimumSize(new java.awt.Dimension(350, 32));
        txtSDT.setPreferredSize(new java.awt.Dimension(350, 30));
        pTimKiem_Row3_Col2.add(txtSDT);

        pTimKiem_Row3.add(pTimKiem_Row3_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem.add(pTimKiem_Row3);

        pTimKiem_Row4.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row4.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row4_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row4_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row4_Col1.setLayout(new java.awt.BorderLayout());

        lblChucVu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblChucVu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChucVu.setText("Chức vụ:");
        lblChucVu.setAlignmentX(20.0F);
        lblChucVu.setAlignmentY(20.0F);
        pTimKiem_Row4_Col1.add(lblChucVu, java.awt.BorderLayout.CENTER);

        pTimKiem_Row4.add(pTimKiem_Row4_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row4_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row4_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row4_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        cboChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboChucVu.setPreferredSize(new java.awt.Dimension(100, 30));
        pTimKiem_Row4_Col2.add(cboChucVu);

        pTimKiem_Row4.add(pTimKiem_Row4_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem.add(pTimKiem_Row4);

        pTimKiem_Row5.setMinimumSize(new java.awt.Dimension(829, 38));
        pTimKiem_Row5.setLayout(new java.awt.BorderLayout());

        pTimKiem_Row5_Col1.setMinimumSize(new java.awt.Dimension(300, 38));
        pTimKiem_Row5_Col1.setPreferredSize(new java.awt.Dimension(500, 38));
        pTimKiem_Row5_Col1.setLayout(new java.awt.BorderLayout());
        pTimKiem_Row5.add(pTimKiem_Row5_Col1, java.awt.BorderLayout.LINE_START);

        pTimKiem_Row5_Col2.setMinimumSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row5_Col2.setPreferredSize(new java.awt.Dimension(669, 38));
        pTimKiem_Row5_Col2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 7));

        btnTim.setBackground(new java.awt.Color(15, 204, 102));
        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTim.setLabel("Tìm kiếm");
        btnTim.setMaximumSize(new java.awt.Dimension(105, 30));
        btnTim.setMinimumSize(new java.awt.Dimension(105, 30));
        btnTim.setPreferredSize(new java.awt.Dimension(105, 30));
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        pTimKiem_Row5_Col2.add(btnTim);

        pTimKiem_Row5.add(pTimKiem_Row5_Col2, java.awt.BorderLayout.CENTER);

        pTimKiem.add(pTimKiem_Row5);

        pNorth.add(pTimKiem, java.awt.BorderLayout.CENTER);

        Panel.add(pNorth, java.awt.BorderLayout.NORTH);

        pCenter.setLayout(new java.awt.BorderLayout());

        scrollTableCenter.setMinimumSize(new java.awt.Dimension(1200, 250));
        scrollTableCenter.setPreferredSize(new java.awt.Dimension(1200, 250));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã nhân viên", "Tên nhân viên", "Chức vụ", "SĐT", "Giới tính", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setMinimumSize(new java.awt.Dimension(1200, 250));
        table.setPreferredSize(new java.awt.Dimension(1200, 250));
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowHorizontalLines(true);
        scrollTableCenter.setViewportView(table);

        pCenter.add(scrollTableCenter, java.awt.BorderLayout.CENTER);

        centerTilte.setBackground(new java.awt.Color(204, 255, 204));
        centerTilte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        centerTilte.setMinimumSize(new java.awt.Dimension(1200, 50));
        centerTilte.setPreferredSize(new java.awt.Dimension(1200, 50));
        centerTilte.setLayout(new java.awt.BorderLayout());

        titleName1.setBackground(new java.awt.Color(0, 0, 0));
        titleName1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleName1.setText("Thông tin nhân viên");
        titleName1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titleName1.setMinimumSize(new java.awt.Dimension(1200, 32));
        titleName1.setPreferredSize(new java.awt.Dimension(1200, 32));
        centerTilte.add(titleName1, java.awt.BorderLayout.CENTER);

        pCenter.add(centerTilte, java.awt.BorderLayout.PAGE_START);

        Panel.add(pCenter, java.awt.BorderLayout.CENTER);

        pSouth.setBackground(new java.awt.Color(222, 222, 222));
        pSouth.setMinimumSize(new java.awt.Dimension(1200, 50));
        pSouth.setPreferredSize(new java.awt.Dimension(1200, 50));

        btnChiTiet.setBackground(new java.awt.Color(15, 204, 102));
        btnChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTiet.setText("Chi tiết");
        btnChiTiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChiTiet.setMaximumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setMinimumSize(new java.awt.Dimension(85, 35));
        btnChiTiet.setPreferredSize(new java.awt.Dimension(105, 35));
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });
        pSouth.add(btnChiTiet);

        Panel.add(pSouth, java.awt.BorderLayout.SOUTH);

        add(Panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if (row < 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn một nhân viên để xem chi tiết!",
                    "Thông báo", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lấy mã nhà cung cấp từ bảng
        String maNV = table.getValueAt(row, 1).toString();

        // Lấy dữ liệu từ DAO
        DAO.NhanVien.NhanVienDAO dao = new DAO.NhanVien.NhanVienDAO();
        Entity.NhanVien.NhanVien nv = dao.findById(maNV).orElse(null);

        if (nv == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Không tìm thấy thông tin nhân viên!",
                    "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Mở form chi tiết
        javax.swing.JFrame parent = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        GUI.form.NhanVien.formThongTinNV dialog = new GUI.form.NhanVien.formThongTinNV(parent, true, nv);

        // Gán dữ liệu vào form
        dialog.setTitle("Thông tin tài khoản - " + nv.getTenNV());
        dialog.setLocationRelativeTo(this);

        dialog.setVisible(true);
        loadDataTable();
    }//GEN-LAST:event_btnChiTietActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String maNV = txtMaNV.getText().trim().toLowerCase();
        String tenNV = txtTenNV.getText().trim().toLowerCase();
        String sdt = txtSDT.getText().trim().toLowerCase();
        String chucVu = cboChucVu.getSelectedItem().toString().trim().toLowerCase();

        // Lấy model
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);  // xoá dữ liệu cũ

        NhanVienDAO dao = new NhanVienDAO();
        List<Object[]> list = dao.search(maNV, tenNV, sdt, chucVu);  // danh sách nhân viên

        // Lọc theo nhiều điều kiện
        list = list.stream()
                .filter(r ->
                        (maNV.isEmpty() || r[0].toString().toLowerCase().contains(maNV)) &&
                        (tenNV.isEmpty() || r[1].toString().toLowerCase().contains(tenNV)) &&
                        (sdt.isEmpty() || r[3].toString().toLowerCase().contains(sdt)) &&
                        (cboChucVu.getSelectedIndex() == 0 ||    // 0 = "Tất cả"
                                r[2].toString().toLowerCase().equals(chucVu))
                )
                .toList();

        // Đổ dữ liệu vào bảng
        int stt = 1;
        for (Object[] r : list) {
            model.addRow(new Object[]{
                    stt++,
                    r[0],   // Mã NV
                    r[1],   // Tên NV
                    r[2],   // Chức vụ
                    r[3],   // SDT
                    r[4],   // Giới tính "Nam"/"Nữ"
                    r[5]    // Trạng thái "Đang làm"/"Nghỉ việc"
            });
        }

        // Thông báo không có kết quả
        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Không tìm thấy nhân viên phù hợp với điều kiện tìm kiếm!");
        }

    }//GEN-LAST:event_btnTimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cboChucVu;
    private javax.swing.JPanel centerTilte;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JPanel northTilte;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pNorth;
    private javax.swing.JPanel pSouth;
    private javax.swing.JPanel pTimKiem;
    private javax.swing.JPanel pTimKiem_Row1;
    private javax.swing.JPanel pTimKiem_Row1_Col1;
    private javax.swing.JPanel pTimKiem_Row1_Col2;
    private javax.swing.JPanel pTimKiem_Row2;
    private javax.swing.JPanel pTimKiem_Row2_Col1;
    private javax.swing.JPanel pTimKiem_Row2_Col2;
    private javax.swing.JPanel pTimKiem_Row3;
    private javax.swing.JPanel pTimKiem_Row3_Col1;
    private javax.swing.JPanel pTimKiem_Row3_Col2;
    private javax.swing.JPanel pTimKiem_Row4;
    private javax.swing.JPanel pTimKiem_Row4_Col1;
    private javax.swing.JPanel pTimKiem_Row4_Col2;
    private javax.swing.JPanel pTimKiem_Row5;
    private javax.swing.JPanel pTimKiem_Row5_Col1;
    private javax.swing.JPanel pTimKiem_Row5_Col2;
    private javax.swing.JScrollPane scrollTableCenter;
    private javax.swing.JTable table;
    private javax.swing.JLabel titleName;
    private javax.swing.JLabel titleName1;
    private java.awt.TextField txtMaNV;
    private java.awt.TextField txtSDT;
    private java.awt.TextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
