/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.form.TaiKhoan;

/**
 *
 * @author ADMIN
 */
public class formThongTinTK extends javax.swing.JDialog {

    /**
     * Creates new form formThongTinTK
     */
    public formThongTinTK(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel = new Swing.RoundPanel();
        pNorth = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        pCenter = new javax.swing.JPanel();
        pThongTin = new javax.swing.JPanel();
        lblTK = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblMK = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblNV = new javax.swing.JLabel();
        cboNhanVien = new javax.swing.JComboBox<String>();
        pSouth = new javax.swing.JPanel();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        roundPanel.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel.setMaximumSize(new java.awt.Dimension(600, 400));
        roundPanel.setName(""); // NOI18N
        roundPanel.setLayout(new java.awt.BorderLayout());

        pNorth.setBackground(new java.awt.Color(204, 255, 204));
        pNorth.setMaximumSize(new java.awt.Dimension(600, 50));
        pNorth.setMinimumSize(new java.awt.Dimension(600, 50));
        pNorth.setPreferredSize(new java.awt.Dimension(600, 50));
        pNorth.setLayout(new java.awt.BorderLayout());

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Thông tin tài khoản");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        title.setMaximumSize(new java.awt.Dimension(190, 32));
        title.setMinimumSize(new java.awt.Dimension(190, 32));
        title.setPreferredSize(new java.awt.Dimension(190, 32));
        pNorth.add(title, java.awt.BorderLayout.CENTER);

        roundPanel.add(pNorth, java.awt.BorderLayout.PAGE_START);

        pCenter.setBackground(new java.awt.Color(255, 255, 255));
        pCenter.setMaximumSize(new java.awt.Dimension(600, 300));
        pCenter.setMinimumSize(new java.awt.Dimension(600, 300));
        pCenter.setPreferredSize(new java.awt.Dimension(600, 300));

        pThongTin.setBackground(new java.awt.Color(255, 255, 255));
        pThongTin.setMaximumSize(new java.awt.Dimension(550, 300));
        pThongTin.setMinimumSize(new java.awt.Dimension(550, 300));
        pThongTin.setPreferredSize(new java.awt.Dimension(550, 300));
        pThongTin.setLayout(new java.awt.GridLayout(4, 2, 5, 0));

        lblTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTK.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTK.setText("Tài khoản:");
        lblTK.setAlignmentX(20.0F);
        lblTK.setAlignmentY(20.0F);
        pThongTin.add(lblTK);

        txtHoTen.setEditable(false);
        txtHoTen.setPreferredSize(new java.awt.Dimension(350, 22));
        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });
        pThongTin.add(txtHoTen);

        lblMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMK.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMK.setText("Mật khẩu:");
        pThongTin.add(lblMK);

        txtPassword.setEditable(false);
        txtPassword.setPreferredSize(new java.awt.Dimension(350, 22));
        pThongTin.add(txtPassword);

        lblNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNV.setText("Nhân viên:");
        pThongTin.add(lblNV);

        cboNhanVien.setEditable(true);
        cboNhanVien.setPreferredSize(new java.awt.Dimension(350, 22));
        pThongTin.add(cboNhanVien);

        pCenter.add(pThongTin);

        roundPanel.add(pCenter, java.awt.BorderLayout.CENTER);

        pSouth.setBackground(new java.awt.Color(255, 255, 255));
        pSouth.setMaximumSize(new java.awt.Dimension(600, 50));
        pSouth.setMinimumSize(new java.awt.Dimension(600, 50));
        pSouth.setPreferredSize(new java.awt.Dimension(600, 50));

        btnHuy.setBackground(new java.awt.Color(255, 103, 102));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Huỷ");
        btnHuy.setPreferredSize(new java.awt.Dimension(90, 35));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        pSouth.add(btnHuy);

        roundPanel.add(pSouth, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(roundPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formThongTinTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formThongTinTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formThongTinTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formThongTinTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                formThongTinTK dialog = new formThongTinTK(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JComboBox<String> cboNhanVien;
    private javax.swing.JLabel lblMK;
    private javax.swing.JLabel lblNV;
    private javax.swing.JLabel lblTK;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pNorth;
    private javax.swing.JPanel pSouth;
    private javax.swing.JPanel pThongTin;
    private Swing.RoundPanel roundPanel;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
