/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.form.TaiKhoan;
import javax.swing.JOptionPane;
import DAO.NhanVien.NhanVienDAO;
import Entity.NhanVien.NhanVien;
import Entity.TaiKhoan.TaiKhoan;
import java.util.List;

/**
 *
 * @author ADMIN
 */
public class formSuaTK extends javax.swing.JDialog {

    /**
     * Creates new form formSuaTK
     * 
     * @param parent
     * @param modal
     * @param tk
     */
    public formSuaTK(java.awt.Frame parent, boolean modal, TaiKhoan tk) {
        super(parent, modal);
        initComponents();
        loadComboBoxData();
        setThongTinTK(tk);
        txtTK.requestFocus();
    }

    private void loadComboBoxData() {
        List<NhanVien> nvDangLam = new NhanVienDAO().findAllDangLam();
        cboNhanVien.removeAllItems();

        for (NhanVien nv : nvDangLam) {
            cboNhanVien.addItem(nv.getMaNV() + " - " + nv.getTenNV());
        }
    }

    private void setThongTinTK(TaiKhoan tk) {
        if (tk != null) {
            txtMaTK.setText(tk.getMaTK());
            txtTK.setText(tk.getTenTK());

            if (tk.getNhanVien() != null) {
                cboNhanVien.setSelectedItem(
                        tk.getNhanVien().getMaNV() + " - " + tk.getNhanVien().getTenNV());
            } else {
                cboNhanVien.setSelectedItem(null);
            }
        } else {
            txtMaTK.setText("");
            txtTK.setText("");
            cboNhanVien.setSelectedItem(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel = new Swing.RoundPanel();
        pNorth = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        pCenter = new javax.swing.JPanel();
        pThongTin = new javax.swing.JPanel();
        lblMaTK = new javax.swing.JLabel();
        txtMaTK = new javax.swing.JTextField();
        lblTK = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        lblMKMoi = new javax.swing.JLabel();
        txtMKMoi = new javax.swing.JTextField();
        lblNhapLaiMK = new javax.swing.JLabel();
        txtNhapLaiMK = new javax.swing.JTextField();
        lblNV = new javax.swing.JLabel();
        cboNhanVien = new javax.swing.JComboBox<String>();
        pSouth = new javax.swing.JPanel();
        btnHuy = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        roundPanel.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel.setMaximumSize(new java.awt.Dimension(600, 400));
        roundPanel.setName(""); // NOI18N
        roundPanel.setLayout(new java.awt.BorderLayout());

        pNorth.setBackground(new java.awt.Color(204, 255, 204));
        pNorth.setMaximumSize(new java.awt.Dimension(600, 50));
        pNorth.setMinimumSize(new java.awt.Dimension(600, 50));
        pNorth.setPreferredSize(new java.awt.Dimension(600, 50));
        pNorth.setLayout(new java.awt.BorderLayout());

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Sửa tài khoản");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        title.setMaximumSize(new java.awt.Dimension(190, 32));
        title.setMinimumSize(new java.awt.Dimension(190, 32));
        title.setPreferredSize(new java.awt.Dimension(190, 32));
        pNorth.add(title, java.awt.BorderLayout.CENTER);

        roundPanel.add(pNorth, java.awt.BorderLayout.PAGE_START);

        pCenter.setBackground(new java.awt.Color(255, 255, 255));
        pCenter.setMaximumSize(new java.awt.Dimension(600, 300));
        pCenter.setMinimumSize(new java.awt.Dimension(600, 300));
        pCenter.setPreferredSize(new java.awt.Dimension(600, 300));

        pThongTin.setBackground(new java.awt.Color(255, 255, 255));
        pThongTin.setMaximumSize(new java.awt.Dimension(550, 300));
        pThongTin.setMinimumSize(new java.awt.Dimension(550, 300));
        pThongTin.setPreferredSize(new java.awt.Dimension(550, 300));
        pThongTin.setLayout(new java.awt.GridLayout(7, 2, 5, 0));

        lblMaTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaTK.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaTK.setText("Mã tài khoản:");
        lblMaTK.setAlignmentX(20.0F);
        lblMaTK.setAlignmentY(20.0F);
        pThongTin.add(lblMaTK);

        txtMaTK.setEditable(false);
        txtMaTK.setPreferredSize(new java.awt.Dimension(350, 22));
        pThongTin.add(txtMaTK);

        lblTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTK.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTK.setText("Tài khoản:");
        lblTK.setAlignmentX(20.0F);
        lblTK.setAlignmentY(20.0F);
        pThongTin.add(lblTK);

        txtTK.setPreferredSize(new java.awt.Dimension(350, 22));
        pThongTin.add(txtTK);

        lblMKMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMKMoi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMKMoi.setText("Mật khẩu mới:");
        pThongTin.add(lblMKMoi);

        txtMKMoi.setPreferredSize(new java.awt.Dimension(350, 22));
        pThongTin.add(txtMKMoi);

        lblNhapLaiMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNhapLaiMK.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNhapLaiMK.setText("Nhập lại mật khẩu: ");
        pThongTin.add(lblNhapLaiMK);

        txtNhapLaiMK.setPreferredSize(new java.awt.Dimension(350, 22));
        pThongTin.add(txtNhapLaiMK);

        lblNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNV.setText("Nhân viên:");
        pThongTin.add(lblNV);

        cboNhanVien.setPreferredSize(new java.awt.Dimension(350, 22));
        pThongTin.add(cboNhanVien);

        pCenter.add(pThongTin);

        roundPanel.add(pCenter, java.awt.BorderLayout.CENTER);

        pSouth.setBackground(new java.awt.Color(255, 255, 255));
        pSouth.setMaximumSize(new java.awt.Dimension(600, 50));
        pSouth.setMinimumSize(new java.awt.Dimension(600, 50));
        pSouth.setPreferredSize(new java.awt.Dimension(600, 50));

        btnHuy.setBackground(new java.awt.Color(255, 103, 102));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Huỷ");
        btnHuy.setPreferredSize(new java.awt.Dimension(90, 35));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        pSouth.add(btnHuy);

        btnSua.setBackground(new java.awt.Color(15, 204, 102));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnSua.setPreferredSize(new java.awt.Dimension(90, 35));
        btnSua.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        pSouth.add(btnSua);

        roundPanel.add(pSouth, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(roundPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        dispose();
    }// GEN-LAST:event_btnHuyActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        try {
            // Lấy dữ liệu từ form
            String tenTK = txtTK.getText().trim();
            String mkMoi = txtMKMoi.getText().trim();
            String nhapLaiMK = txtNhapLaiMK.getText().trim();
            String nvSelected = (String) cboNhanVien.getSelectedItem();

            // 1. Kiểm tra tên tài khoản
            if (tenTK.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tên tài khoản!");
                return;
            }

            String regexTenTK = "^[a-zA-Z][a-zA-Z0-9_.]{2,49}$"; // 3-50 ký tự
            if (!tenTK.matches(regexTenTK)) {
                JOptionPane.showMessageDialog(this,
                        "Tên tài khoản không hợp lệ!\n"
                                + "• Bắt đầu bằng chữ\n"
                                + "• Dài 3–50 ký tự\n"
                                + "• Chỉ chứa chữ, số, dấu _ hoặc .");
                return;
            }

            // 2. Kiểm tra mật khẩu mới
            if (mkMoi.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu mới!");
                return;
            }

            // Regex: ít nhất 1 chữ thường, 1 chữ hoa, 1 số, 1 ký tự đặc biệt, độ dài 6-50
            String regexMK = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&]).{6,50}$";
            if (!mkMoi.matches(regexMK)) {
                JOptionPane.showMessageDialog(this,
                        "Mật khẩu không hợp lệ!\n"
                                + "• Có ít nhất 1 chữ hoa\n"
                                + "• Có ít nhất 1 chữ thường\n"
                                + "• Có ít nhất 1 số\n"
                                + "• Có ít nhất 1 ký tự đặc biệt (@$!%*?&)\n"
                                + "• Độ dài từ 6 đến 50 ký tự");
                return;
            }

            // 3. Kiểm tra nhập lại mật khẩu
            if (!mkMoi.equals(nhapLaiMK)) {
                JOptionPane.showMessageDialog(this, "Mật khẩu nhập lại không khớp!");
                return;
            }

            // 4. Lấy đối tượng NhanVien từ combo box
            Entity.NhanVien.NhanVien nv = null;
            if (nvSelected != null && !nvSelected.isEmpty()) {
                String maNV = nvSelected.split(" - ")[0].trim();
                nv = new DAO.NhanVien.NhanVienDAO().findById(maNV).orElse(null);
            }

            if (nv == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên!");
                return;
            }

            // 5. Tạo đối tượng TaiKhoan để update
            Entity.TaiKhoan.TaiKhoan tk = new Entity.TaiKhoan.TaiKhoan();
            tk.setMaTK(txtMaTK.getText().trim());
            tk.setTenTK(tenTK);
            tk.setMatKhauTK(mkMoi);
            tk.setNhanVien(nv);

            // 6. Cập nhật database
            DAO.TaiKhoan.TaiKhoanDAO dao = new DAO.TaiKhoan.TaiKhoanDAO();
            if (dao.update(tk)) {
                JOptionPane.showMessageDialog(this, "Cập nhật tài khoản thành công!");
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi cập nhật tài khoản!");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra, vui lòng kiểm tra lại dữ liệu!");
        }
    }// GEN-LAST:event_btnSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // /* Set the Nimbus look and feel */
        // //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        // /* If Nimbus (introduced in Java SE 6) is not available, stay with the
        // default look and feel.
        // * For details see
        // http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        // */
        // try {
        // for (javax.swing.UIManager.LookAndFeelInfo info :
        // javax.swing.UIManager.getInstalledLookAndFeels()) {
        // if ("Nimbus".equals(info.getName())) {
        // javax.swing.UIManager.setLookAndFeel(info.getClassName());
        // break;
        // }
        // }
        // } catch (ClassNotFoundException ex) {
        // java.util.logging.Logger.getLogger(formSuaTK.class.getName()).log(java.util.logging.Level.SEVERE,
        // null, ex);
        // } catch (InstantiationException ex) {
        // java.util.logging.Logger.getLogger(formSuaTK.class.getName()).log(java.util.logging.Level.SEVERE,
        // null, ex);
        // } catch (IllegalAccessException ex) {
        // java.util.logging.Logger.getLogger(formSuaTK.class.getName()).log(java.util.logging.Level.SEVERE,
        // null, ex);
        // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        // java.util.logging.Logger.getLogger(formSuaTK.class.getName()).log(java.util.logging.Level.SEVERE,
        // null, ex);
        // }
        // //</editor-fold>
        //
        // /* Create and display the dialog */
        // java.awt.EventQueue.invokeLater(new Runnable() {
        // public void run() {
        // formSuaTK dialog = new formSuaTK(new javax.swing.JFrame(), true);
        // dialog.addWindowListener(new java.awt.event.WindowAdapter() {
        // @Override
        // public void windowClosing(java.awt.event.WindowEvent e) {
        // System.exit(0);
        // }
        // });
        // dialog.setVisible(true);
        // }
        // });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnSua;
    private javax.swing.JComboBox<String> cboNhanVien;
    private javax.swing.JLabel lblMKMoi;
    private javax.swing.JLabel lblMaTK;
    private javax.swing.JLabel lblNV;
    private javax.swing.JLabel lblNhapLaiMK;
    private javax.swing.JLabel lblTK;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pNorth;
    private javax.swing.JPanel pSouth;
    private javax.swing.JPanel pThongTin;
    private Swing.RoundPanel roundPanel;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtMKMoi;
    private javax.swing.JTextField txtMaTK;
    private javax.swing.JTextField txtNhapLaiMK;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables
}
