/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.form.SanPham;

import java.io.IOException;
import java.time.ZoneId;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import DAO.SanPham.DanhMucDAO;
import DAO.SanPham.DonViTinhDAO;
import DAO.SanPham.SanPhamDAO;
import DAO.SanPham.XuatXuDAO;
import Entity.SanPham.DanhMuc;
import Entity.SanPham.DonViTinh;
import Entity.SanPham.SanPham;
import Entity.SanPham.XuatXu;
import java.awt.Graphics2D;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.util.Date;
import java.util.List;

/**
 *
 * @author ADMIN
 */
public final class formSuaSP extends javax.swing.JDialog {
    private byte[] imageData = null;

    /**
     * Creates new form formSuaSP
     * 
     * @param parent
     * @param modal
     * @param sp
     */
    public formSuaSP(java.awt.Frame parent, boolean modal, SanPham sp) {
        super(parent, modal);
        initComponents();
        loadComboBoxData();
        setThongTinSP(sp);
    }

    private void loadComboBoxData() {
        List<DanhMuc> danhMucList = new DanhMucDAO().findAll();
        for (DanhMuc dm : danhMucList) {
            cboDanhMuc.addItem(dm.getTenDM().trim());
        }

        List<DonViTinh> dvtList = new DonViTinhDAO().findAll();
        for (DonViTinh dvt : dvtList) {
            cboDVT.addItem(dvt.getTenDVT().trim());
        }

        List<XuatXu> xxList = new XuatXuDAO().findAll();
        for (XuatXu xx : xxList) {
            cboXuatXu.addItem(xx.getTenXX().trim());
        }
    }

    public void setThongTinSP(Entity.SanPham.SanPham sp) {
        if (sp != null) {
            txtMaSP.setText(sp.getMaSP());
            txtTenSP.setText(sp.getTenSP());
            txtGiaNhap.setText(String.valueOf(sp.getGiaNhap()));
            txtGiaBan.setText(String.valueOf(sp.getDonGia()));
            txtSoLuong.setText(String.valueOf(sp.getSoLuong()));
            txtMoTa.setText(sp.getMoTaSP());
            DateHSD.setDate(
                    sp.getHsd() != null ? Date.from(sp.getHsd().atZone(ZoneId.systemDefault()).toInstant()) : null);

            cboDanhMuc.setSelectedItem(sp.getDanhMuc().getTenDM());
            cboDVT.setSelectedItem(sp.getDonViTinh().getTenDVT());
            cboXuatXu.setSelectedItem(sp.getXuatXu().getTenXX());

            lblAnh.setIcon(sp.getAnhSP() != null ? new ImageIcon(sp.getAnhSP()) : new FlatSVGIcon("./icon/image.svg"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel = new Swing.RoundPanel();
        pNorth = new javax.swing.JPanel();
        tilte = new javax.swing.JLabel();
        pCenter = new javax.swing.JPanel();
        pThongTin = new javax.swing.JPanel();
        lblSP = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        lblTen = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        lblGiaNhap = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        lblGiaBan = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        lblHSD = new javax.swing.JLabel();
        DateHSD = new com.toedter.calendar.JDateChooser();
        lblMoTa = new javax.swing.JLabel();
        jspMoTa = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        lblDanhMuc = new javax.swing.JLabel();
        cboDanhMuc = new javax.swing.JComboBox<>();
        lblDonViTinh = new javax.swing.JLabel();
        cboDVT = new javax.swing.JComboBox<>();
        lblXuatXu = new javax.swing.JLabel();
        cboXuatXu = new javax.swing.JComboBox<>();
        lblSoLuong = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        pSouth = new javax.swing.JPanel();
        btnHuy = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        pWest = new javax.swing.JPanel();
        anh = new javax.swing.JPanel();
        lblAnh = new javax.swing.JLabel();
        btnAnh = new javax.swing.JPanel();
        btnThemAnh = new javax.swing.JButton();
        pEast = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));

        roundPanel.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel.setMaximumSize(new java.awt.Dimension(700, 450));
        roundPanel.setMinimumSize(new java.awt.Dimension(700, 450));
        roundPanel.setName(""); // NOI18N
        roundPanel.setPreferredSize(new java.awt.Dimension(700, 450));
        roundPanel.setLayout(new java.awt.BorderLayout());

        pNorth.setBackground(new java.awt.Color(204, 255, 204));
        pNorth.setMaximumSize(new java.awt.Dimension(700, 50));
        pNorth.setName(""); // NOI18N
        pNorth.setLayout(new java.awt.GridLayout(1, 0));

        tilte.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tilte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tilte.setText("Sửa sản phẩm");
        tilte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tilte.setMaximumSize(new java.awt.Dimension(700, 50));
        tilte.setMinimumSize(new java.awt.Dimension(700, 50));
        tilte.setPreferredSize(new java.awt.Dimension(700, 50));
        pNorth.add(tilte);

        roundPanel.add(pNorth, java.awt.BorderLayout.NORTH);

        pCenter.setMaximumSize(new java.awt.Dimension(440, 350));
        pCenter.setLayout(new java.awt.BorderLayout());

        pThongTin.setBackground(new java.awt.Color(255, 255, 255));
        pThongTin.setMaximumSize(new java.awt.Dimension(440, 350));
        pThongTin.setMinimumSize(new java.awt.Dimension(440, 350));
        pThongTin.setName(""); // NOI18N
        pThongTin.setPreferredSize(new java.awt.Dimension(440, 350));
        pThongTin.setLayout(new java.awt.GridLayout(11, 1, 5, 0));

        lblSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSP.setText("Mã sản phẩm:");
        lblSP.setAlignmentX(20.0F);
        lblSP.setAlignmentY(20.0F);
        lblSP.setMaximumSize(new java.awt.Dimension(300, 20));
        lblSP.setMinimumSize(new java.awt.Dimension(300, 20));
        lblSP.setPreferredSize(new java.awt.Dimension(300, 20));
        pThongTin.add(lblSP);

        txtMaSP.setEditable(false);
        txtMaSP.setMaximumSize(new java.awt.Dimension(300, 20));
        txtMaSP.setMinimumSize(new java.awt.Dimension(300, 20));
        txtMaSP.setPreferredSize(new java.awt.Dimension(300, 20));
        pThongTin.add(txtMaSP);

        lblTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTen.setText("Tên sản phẩm:");
        lblTen.setAlignmentX(20.0F);
        lblTen.setAlignmentY(20.0F);
        pThongTin.add(lblTen);

        txtTenSP.setPreferredSize(new java.awt.Dimension(350, 22));
        pThongTin.add(txtTenSP);

        lblGiaNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGiaNhap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGiaNhap.setText("Giá nhập:");
        lblGiaNhap.setToolTipText("");
        lblGiaNhap.setMaximumSize(new java.awt.Dimension(170, 38));
        lblGiaNhap.setMinimumSize(new java.awt.Dimension(170, 38));
        lblGiaNhap.setPreferredSize(new java.awt.Dimension(170, 38));
        pThongTin.add(lblGiaNhap);

        txtGiaNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtGiaNhap.setPreferredSize(new java.awt.Dimension(250, 30));
        txtGiaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaNhapActionPerformed(evt);
            }
        });
        pThongTin.add(txtGiaNhap);

        lblGiaBan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGiaBan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGiaBan.setText("Giá bán:");
        lblGiaBan.setToolTipText("");
        lblGiaBan.setMaximumSize(new java.awt.Dimension(170, 38));
        lblGiaBan.setMinimumSize(new java.awt.Dimension(170, 38));
        lblGiaBan.setPreferredSize(new java.awt.Dimension(170, 38));
        pThongTin.add(lblGiaBan);

        txtGiaBan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtGiaBan.setPreferredSize(new java.awt.Dimension(250, 30));
        pThongTin.add(txtGiaBan);

        lblHSD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHSD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHSD.setText("HSD:");
        lblHSD.setMaximumSize(new java.awt.Dimension(170, 38));
        lblHSD.setMinimumSize(new java.awt.Dimension(170, 38));
        lblHSD.setPreferredSize(new java.awt.Dimension(170, 38));
        pThongTin.add(lblHSD);

        DateHSD.setBackground(new java.awt.Color(255, 255, 255));
        DateHSD.setDateFormatString("dd, MM,yyyy");
        DateHSD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DateHSD.setMinimumSize(new java.awt.Dimension(140, 30));
        DateHSD.setPreferredSize(new java.awt.Dimension(140, 30));
        pThongTin.add(DateHSD);

        lblMoTa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMoTa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMoTa.setText("Mô tả:");
        lblMoTa.setToolTipText("");
        lblMoTa.setMaximumSize(new java.awt.Dimension(170, 38));
        lblMoTa.setMinimumSize(new java.awt.Dimension(170, 38));
        lblMoTa.setPreferredSize(new java.awt.Dimension(170, 38));
        pThongTin.add(lblMoTa);

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jspMoTa.setViewportView(txtMoTa);

        pThongTin.add(jspMoTa);

        lblDanhMuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDanhMuc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDanhMuc.setText("Danh mục:");
        lblDanhMuc.setMaximumSize(new java.awt.Dimension(170, 38));
        lblDanhMuc.setMinimumSize(new java.awt.Dimension(170, 38));
        lblDanhMuc.setPreferredSize(new java.awt.Dimension(170, 38));
        pThongTin.add(lblDanhMuc);

        cboDanhMuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cboDanhMuc.setPreferredSize(new java.awt.Dimension(250, 22));
        pThongTin.add(cboDanhMuc);

        lblDonViTinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDonViTinh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDonViTinh.setText("Đơn vị tính:");
        lblDonViTinh.setMaximumSize(new java.awt.Dimension(170, 38));
        lblDonViTinh.setMinimumSize(new java.awt.Dimension(170, 38));
        lblDonViTinh.setPreferredSize(new java.awt.Dimension(170, 38));
        pThongTin.add(lblDonViTinh);

        cboDVT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cboDVT.setPreferredSize(new java.awt.Dimension(250, 22));
        pThongTin.add(cboDVT);

        lblXuatXu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblXuatXu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblXuatXu.setText("Xuất xứ:");
        lblXuatXu.setMaximumSize(new java.awt.Dimension(170, 38));
        lblXuatXu.setMinimumSize(new java.awt.Dimension(170, 38));
        lblXuatXu.setPreferredSize(new java.awt.Dimension(170, 38));
        pThongTin.add(lblXuatXu);

        cboXuatXu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cboXuatXu.setPreferredSize(new java.awt.Dimension(250, 22));
        pThongTin.add(cboXuatXu);

        lblSoLuong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSoLuong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSoLuong.setText("Số lượng:");
        lblSoLuong.setMaximumSize(new java.awt.Dimension(170, 38));
        lblSoLuong.setMinimumSize(new java.awt.Dimension(170, 38));
        lblSoLuong.setPreferredSize(new java.awt.Dimension(180, 38));
        pThongTin.add(lblSoLuong);

        txtSoLuong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSoLuong.setMinimumSize(new java.awt.Dimension(350, 22));
        txtSoLuong.setPreferredSize(new java.awt.Dimension(250, 30));
        pThongTin.add(txtSoLuong);

        pCenter.add(pThongTin, java.awt.BorderLayout.CENTER);

        roundPanel.add(pCenter, java.awt.BorderLayout.CENTER);

        pSouth.setBackground(new java.awt.Color(255, 255, 255));
        pSouth.setMaximumSize(new java.awt.Dimension(700, 50));
        pSouth.setMinimumSize(new java.awt.Dimension(700, 50));
        pSouth.setPreferredSize(new java.awt.Dimension(700, 50));

        btnHuy.setBackground(new java.awt.Color(255, 103, 102));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Huỷ");
        btnHuy.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnHuy.setPreferredSize(new java.awt.Dimension(90, 35));
        btnHuy.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        pSouth.add(btnHuy);

        btnSua.setBackground(new java.awt.Color(15, 204, 102));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnSua.setPreferredSize(new java.awt.Dimension(90, 35));
        btnSua.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        pSouth.add(btnSua);

        roundPanel.add(pSouth, java.awt.BorderLayout.SOUTH);

        pWest.setBackground(new java.awt.Color(255, 255, 255));
        pWest.setMaximumSize(new java.awt.Dimension(250, 350));
        pWest.setMinimumSize(new java.awt.Dimension(250, 350));
        pWest.setLayout(new java.awt.BorderLayout());

        anh.setBackground(new java.awt.Color(255, 255, 255));
        anh.setMinimumSize(new java.awt.Dimension(100, 211));
        anh.setLayout(new java.awt.BorderLayout());

        lblAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh.setToolTipText("");
        lblAnh.setAutoscrolls(true);
        anh.add(lblAnh, java.awt.BorderLayout.CENTER);

        pWest.add(anh, java.awt.BorderLayout.CENTER);

        btnAnh.setBackground(new java.awt.Color(255, 255, 255));

        btnThemAnh.setBackground(new java.awt.Color(204, 204, 204));
        btnThemAnh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemAnh.setText("Thêm ảnh");
        btnThemAnh.setPreferredSize(new java.awt.Dimension(13, 13));
        btnThemAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemAnhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnAnhLayout = new javax.swing.GroupLayout(btnAnh);
        btnAnh.setLayout(btnAnhLayout);
        btnAnhLayout.setHorizontalGroup(
                btnAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btnAnhLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(btnThemAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 97,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(80, Short.MAX_VALUE)));
        btnAnhLayout.setVerticalGroup(
                btnAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btnAnhLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnThemAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pWest.add(btnAnh, java.awt.BorderLayout.SOUTH);

        roundPanel.add(pWest, java.awt.BorderLayout.WEST);

        pEast.setBackground(new java.awt.Color(255, 255, 255));
        pEast.setMaximumSize(new java.awt.Dimension(20, 350));
        pEast.setMinimumSize(new java.awt.Dimension(20, 350));

        javax.swing.GroupLayout pEastLayout = new javax.swing.GroupLayout(pEast);
        pEast.setLayout(pEastLayout);
        pEastLayout.setHorizontalGroup(
                pEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 20, Short.MAX_VALUE));
        pEastLayout.setVerticalGroup(
                pEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 350, Short.MAX_VALUE));

        roundPanel.add(pEast, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 700, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(roundPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 450, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(roundPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGiaNhapActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtGiaNhapActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtGiaNhapActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        dispose();
    }// GEN-LAST:event_btnHuyActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        try {
            // Kiểm tra các trường không để trống
            if (txtTenSP.getText().isEmpty() || txtGiaNhap.getText().isEmpty() ||
                    txtGiaBan.getText().isEmpty() || txtSoLuong.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin sản phẩm.");
                return;
            }

            // Lấy thông tin từ form
            String tenSP = txtTenSP.getText();
            String moTa = txtMoTa.getText();
            String giaNhapStr = txtGiaNhap.getText();
            String giaBanStr = txtGiaBan.getText();
            String soLuongStr = txtSoLuong.getText();
            Date hsd = DateHSD.getDate(); // Lấy hạn sử dụng
            String danhMuc = (String) cboDanhMuc.getSelectedItem();
            String donViTinh = (String) cboDVT.getSelectedItem();
            String xuatXu = (String) cboXuatXu.getSelectedItem();

            // --- Bắt đầu kiểm tra dữ liệu nhập ---
            if (tenSP.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tên sản phẩm!");
                return;
            }

            if (giaNhapStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập giá nhập của sản phẩm!");
                return;
            }
            if (!giaNhapStr.matches("^\\d+(\\.\\d+)?$")) {
                JOptionPane.showMessageDialog(this, "Giá nhập chỉ được nhập số và không chứa chữ hoặc ký tự đặc biệt!");
                return;
            }

            if (giaBanStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập giá bán của sản phẩm!");
                return;
            }
            if (!giaBanStr.matches("^\\d+(\\.\\d+)?$")) {
                JOptionPane.showMessageDialog(this, "Giá bán chỉ được nhập số và không chứa chữ hoặc ký tự đặc biệt!");
                return;
            }

            double giaNhap = Double.parseDouble(giaNhapStr);
            double giaBan = Double.parseDouble(giaBanStr);

            if (giaNhap < 0 || giaBan < 0) {
                JOptionPane.showMessageDialog(this, "Giá nhập và giá bán phải lớn hơn hoặc bằng 0!");
                return;
            }
            if (giaNhap > giaBan) {
                JOptionPane.showMessageDialog(this, "Giá nhập phải thấp hơn giá bán!");
                return;
            }

            if (soLuongStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng của sản phẩm!");
                return;
            }
            if (!soLuongStr.matches("^\\d+$")) {
                JOptionPane.showMessageDialog(this,
                        "Số lượng phải là số nguyên không âm và không được chứa chữ hoặc dấu thập phân!");
                return;
            }

            int soLuong = Integer.parseInt(soLuongStr);

            if (soLuong < 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn hoặc bằng 0!");
                return;
            }

            if (hsd == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn hạn sử dụng!");
                return;
            }
            Date today = new Date();
            if (!hsd.after(today)) {
                JOptionPane.showMessageDialog(this, "Hạn sử dụng phải là ngày sau hôm nay!");
                return;
            }
            // --- Kết thúc kiểm tra dữ liệu nhập ---

            if (danhMuc == null || donViTinh == null || xuatXu == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn đầy đủ danh mục, đơn vị tính và xuất xứ!");
                return;
            }

            String maDanhMuc = new DanhMucDAO().findAll().stream()
                    .filter(dm -> dm.getTenDM() != null && dm.getTenDM().trim().equalsIgnoreCase(danhMuc.trim()))
                    .map(DanhMuc::getMaDM)
                    .findFirst().orElse(null);

            String maDVT = new DonViTinhDAO().findAll().stream()
                    .filter(dvt -> dvt.getTenDVT() != null && dvt.getTenDVT().trim().equalsIgnoreCase(donViTinh.trim()))
                    .map(DonViTinh::getMaDVT)
                    .findFirst().orElse(null);

            String maXuatXu = new XuatXuDAO().findAll().stream()
                    .filter(xx -> xx.getTenXX() != null && xx.getTenXX().trim().equalsIgnoreCase(xuatXu.trim()))
                    .map(XuatXu::getMaXX)
                    .findFirst().orElse(null);

            // Tạo đối tượng SanPham để cập nhật
            SanPham sanPham = new SanPham(
                    txtMaSP.getText(), // Mã sản phẩm
                    tenSP, // Tên sản phẩm
                    imageData, // Ảnh (byte[])
                    moTa, // Mô tả sản phẩm
                    new DanhMuc(maDanhMuc, danhMuc),
                    new DonViTinh(maDVT, donViTinh),
                    new XuatXu(maXuatXu, xuatXu),
                    soLuong, // Số lượng
                    new java.math.BigDecimal(giaNhap),
                    new java.math.BigDecimal(giaBan),
                    hsd.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDateTime());

            // Cập nhật thông tin sản phẩm vào cơ sở dữ liệu
            if (new SanPhamDAO().update(sanPham)) {
                JOptionPane.showMessageDialog(this, "Sửa sản phẩm thành công!");
                dispose(); // Đóng form sau khi sửa thành công
            } else {
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi sửa sản phẩm.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giá trị hợp lệ cho giá nhập, giá bán và số lượng.");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi sửa sản phẩm. Vui lòng kiểm tra lại dữ liệu.");
        }
    }// GEN-LAST:event_btnSuaActionPerformed

    private void btnThemAnhActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThemAnhActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn ảnh sản phẩm");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Ảnh (JPG, PNG, JPEG)", "jpg", "jpeg", "png"));

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            try {
                // Đọc ảnh gốc
                BufferedImage originalImage = ImageIO.read(selectedFile);
                if (originalImage == null) {
                    JOptionPane.showMessageDialog(this, "Không thể đọc định dạng ảnh này!");
                    return;
                }

                // Kích thước hiển thị cố định
                int targetWidth = 250;
                int targetHeight = 250;

                // Tính tỷ lệ để không méo ảnh
                double aspectRatio = (double) originalImage.getWidth() / originalImage.getHeight();
                int newWidth = targetWidth;
                int newHeight = (int) (targetWidth / aspectRatio);

                if (newHeight > targetHeight) {
                    newHeight = targetHeight;
                    newWidth = (int) (targetHeight * aspectRatio);
                }

                // Scale ảnh về kích thước phù hợp
                Image scaledImage = originalImage.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);

                // Tạo ảnh đích có nền trong suốt (TYPE_INT_ARGB)
                BufferedImage finalImage = new BufferedImage(targetWidth, targetHeight, BufferedImage.TYPE_INT_ARGB);
                Graphics2D g2d = finalImage.createGraphics();

                // Không dùng Color.WHITE, chỉ vẽ ảnh vào giữa khung
                int x = (targetWidth - newWidth) / 2;
                int y = (targetHeight - newHeight) / 2;
                g2d.drawImage(scaledImage, x, y, null);
                g2d.dispose();

                // Gán lên JLabel
                lblAnh.setIcon(new ImageIcon(finalImage));

                // Chuyển ảnh sang mảng byte để lưu DB
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                ImageIO.write(finalImage, "png", baos);
                baos.flush();
                imageData = baos.toByteArray();
                baos.close();

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi đọc ảnh: " + e.getMessage());
            }
        }
    }// GEN-LAST:event_btnThemAnhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * // * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         * //
         */
        // try {
        // for (javax.swing.UIManager.LookAndFeelInfo info :
        // javax.swing.UIManager.getInstalledLookAndFeels()) {
        // if ("Nimbus".equals(info.getName())) {
        // javax.swing.UIManager.setLookAndFeel(info.getClassName());
        // break;
        // }
        // }
        // } catch (ClassNotFoundException ex) {
        // java.util.logging.Logger.getLogger(formSuaSP.class.getName()).log(java.util.logging.Level.SEVERE,
        // null, ex);
        // } catch (InstantiationException ex) {
        // java.util.logging.Logger.getLogger(formSuaSP.class.getName()).log(java.util.logging.Level.SEVERE,
        // null, ex);
        // } catch (IllegalAccessException ex) {
        // java.util.logging.Logger.getLogger(formSuaSP.class.getName()).log(java.util.logging.Level.SEVERE,
        // null, ex);
        // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        // java.util.logging.Logger.getLogger(formSuaSP.class.getName()).log(java.util.logging.Level.SEVERE,
        // null, ex);
        // }
        // // </editor-fold>
        //
        // /* Create and display the dialog */
        // java.awt.EventQueue.invokeLater(new Runnable() {
        // public void run() {
        // formSuaSP dialog = new formSuaSP(new javax.swing.JFrame(), true);
        // dialog.addWindowListener(new java.awt.event.WindowAdapter() {
        // @Override
        // public void windowClosing(java.awt.event.WindowEvent e) {
        // System.exit(0);
        // }
        // });
        // dialog.setVisible(true);
        // }
        // });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateHSD;
    private javax.swing.JPanel anh;
    private javax.swing.JPanel btnAnh;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemAnh;
    private javax.swing.JComboBox<String> cboDVT;
    private javax.swing.JComboBox<String> cboDanhMuc;
    private javax.swing.JComboBox<String> cboXuatXu;
    private javax.swing.JScrollPane jspMoTa;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblDanhMuc;
    private javax.swing.JLabel lblDonViTinh;
    private javax.swing.JLabel lblGiaBan;
    private javax.swing.JLabel lblGiaNhap;
    private javax.swing.JLabel lblHSD;
    private javax.swing.JLabel lblMoTa;
    private javax.swing.JLabel lblSP;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblXuatXu;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pEast;
    private javax.swing.JPanel pNorth;
    private javax.swing.JPanel pSouth;
    private javax.swing.JPanel pThongTin;
    private javax.swing.JPanel pWest;
    private Swing.RoundPanel roundPanel;
    private javax.swing.JLabel tilte;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
